import React from 'react';
import { ChevronRight, Search, Star } from 'lucide-react';
import { ReportItem } from './reportTypes';

interface ReportCardGridProps {
  activeGroup: string;
  searchQuery: string;
  setSearchQuery: (val: string) => void;
  filteredReports: ReportItem[];
  dateRange: string;
  onSelectReport: (id: string) => void;
  onToggleFavorite: (id: string, e: React.MouseEvent) => void;
}

export const ReportCardGrid: React.FC<ReportCardGridProps> = ({
  activeGroup,
  searchQuery,
  setSearchQuery,
  filteredReports,
  dateRange,
  onSelectReport,
  onToggleFavorite,
}) => {
  return (
    <div className="p-3 sm:p-6 space-y-4 sm:space-y-6 flex-1 flex flex-col">
      {/* Top Header & Search bar */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3 border-b border-slate-200 dark:border-slate-800 pb-3">
        <div>
          <h2 className="text-lg sm:text-xl font-bold text-slate-900 dark:text-slate-100 flex items-center space-x-2">
            <span>
              {activeGroup === 'home'
                ? 'All Reports'
                : activeGroup === 'favorites'
                ? 'Favorite Reports'
                : `${activeGroup} Reports`}
            </span>
            <span className="text-xs font-semibold bg-blue-50 text-blue-700 dark:bg-blue-950 dark:text-blue-300 border border-blue-200 dark:border-blue-800 px-2.5 py-0.5 rounded-full">
              {filteredReports.length}
            </span>
          </h2>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
            Every listed report is generated by a tenant-scoped server query over posted accounting data
          </p>
        </div>

        {/* Search Box */}
        <div className="relative w-full sm:w-72">
          <Search className="w-4 h-4 absolute left-3 top-2.5 text-slate-400 pointer-events-none" />
          <input
            type="text"
            placeholder="Search report name or keyword..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 pl-9 pr-4 py-2 rounded-xl text-xs font-medium focus:outline-hidden focus:ring-2 focus:ring-blue-500"
          />
        </div>
      </div>

      {/* Responsive report catalog */}
      <div className="grid grid-cols-1 gap-2.5 lg:grid-cols-2 lg:gap-4 lg:overflow-y-auto lg:p-1 xl:grid-cols-3">
        {filteredReports.length === 0 ? (
          <div className="p-6 text-center text-slate-400 dark:text-slate-500 italic bg-slate-50 dark:bg-slate-800/50 rounded-xl text-xs lg:col-span-full lg:p-12">
            No reports found matching your criteria.
          </div>
        ) : (
          filteredReports.map((report) => (
            <div
              key={report.id}
              onClick={() => onSelectReport(report.id)}
              className="group flex cursor-pointer flex-col justify-between space-y-2 rounded-2xl border border-slate-200/90 bg-white p-3.5 shadow-2xs transition-all active:bg-blue-50/50 lg:p-4 lg:hover:border-blue-300 lg:hover:shadow-md dark:border-slate-800 dark:bg-slate-900 dark:active:bg-slate-800 dark:lg:hover:border-blue-700"
            >
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <span className="rounded border border-blue-200 bg-blue-50 px-2 py-0.5 text-[10px] font-bold text-blue-700 lg:rounded-lg lg:border-slate-200 lg:bg-slate-100 lg:font-extrabold lg:uppercase lg:text-slate-600 dark:border-blue-800 dark:bg-blue-950/80 dark:text-blue-300 dark:lg:border-slate-700 dark:lg:bg-slate-800 dark:lg:text-slate-300">
                    {report.category}
                  </span>
                  <button
                    type="button"
                    onClick={(e) => onToggleFavorite(report.id, e)}
                    className="p-1 text-slate-300 hover:text-amber-500 transition-colors cursor-pointer"
                    title="Toggle Favorite"
                  >
                    <Star
                      className={`w-4 h-4 ${
                        report.isFavorite ? 'text-amber-500 fill-amber-500' : ''
                      }`}
                    />
                  </button>
                </div>

                <h3 className="text-xs font-bold leading-tight text-slate-900 transition-colors group-hover:text-blue-600 lg:text-sm dark:text-slate-100 dark:group-hover:text-blue-400">
                  {report.name}
                </h3>

                <p className="line-clamp-2 text-[10px] leading-relaxed text-slate-500 lg:text-xs dark:text-slate-400">
                  {report.description}
                </p>
              </div>

              <div className="mt-1.5 flex items-center justify-between border-t border-slate-100 pt-1.5 dark:border-slate-800 lg:mt-3 lg:pt-3">
                <span className="text-[10px] font-medium text-slate-400">
                  <span className="lg:hidden">By {report.createdBy}</span>
                  <span className="hidden lg:inline">Period: {dateRange}</span>
                </span>
                <span className="flex items-center space-x-1 rounded-lg bg-blue-50 px-2 py-1 text-[10px] font-bold text-blue-600 transition-transform group-hover:translate-x-0.5 lg:bg-transparent lg:p-0 lg:text-xs dark:bg-blue-950/80 dark:text-blue-400 dark:lg:bg-transparent">
                  <span className="lg:hidden">View Statement</span>
                  <span className="hidden lg:inline">Run Report</span>
                  <ChevronRight className="w-3.5 h-3.5" />
                </span>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
};
