import {
  Account,
  Client,
  Estimate,
  Expense,
  FirmSettings,
  Invoice,
  JournalEntry,
  Project,
  Salesperson,
  TimeEntry,
  Vendor,
} from '../types';

export const initialSalespersons: Salesperson[] = [
  {
    id: 'sp-1',
    name: 'David Vance',
    code: 'SP-001',
    email: 'david.vance@apexgrowth.com',
    phone: '+1 (555) 234-5678',
    commissionRate: 5.0,
    status: 'Active',
    region: 'North America West',
    notes: 'Top performer in Tech Enterprise Accounts',
    createdAt: '2025-01-15',
  },
  {
    id: 'sp-2',
    name: 'Sarah Jenkins',
    code: 'SP-002',
    email: 'sarah.jenkins@apexgrowth.com',
    phone: '+1 (555) 876-5432',
    commissionRate: 7.5,
    status: 'Active',
    region: 'North America East',
    notes: 'Specializes in Financial & Professional Services',
    createdAt: '2025-02-01',
  },
  {
    id: 'sp-3',
    name: 'Michael Chang',
    code: 'SP-003',
    email: 'michael.chang@apexgrowth.com',
    phone: '+1 (555) 345-6789',
    commissionRate: 4.0,
    status: 'Active',
    region: 'APAC / Global',
    notes: 'Handles Key International Strategic Accounts',
    createdAt: '2025-03-10',
  },
  {
    id: 'sp-4',
    name: 'Elena Rostova',
    code: 'SP-004',
    email: 'elena.rostova@apexgrowth.com',
    phone: '+1 (555) 987-6543',
    commissionRate: 5.0,
    status: 'Inactive',
    region: 'EMEA',
    notes: 'On sabbatical leave',
    createdAt: '2024-11-20',
  },
];

export const initialSettings: FirmSettings = {
  firmName: 'Sense studios design',
  firmEmail: 'chintalarayudu1@gmail.com',
  firmPhone: '',
  firmAddress: 'Chintalarayudu1, Taraka Ramanagar 3rd line, Siri nilayam., Guntur, AP - 522006',
  taxId: '37AAAAA0000A1Z5',
  currencySymbol: '₹',
  currencyCode: 'INR',
  defaultTaxRate: 18.0,
  fiscalYearStart: 'April',
  logoText: 'Sense Studios Design',

  orgProfileDetails: {
    logoUrl: '',
    logoFileName: '',
    organizationName: 'Sense studios design',
    industry: 'Construction',
    locationCountry: 'India',
    addressLine1: 'Chintalarayudu1',
    addressLine2: 'Taraka Ramanagar 3rd line, Siri nilayam.',
    city: 'Guntur',
    state: 'Andhra Pradesh',
    zipCode: '522006',
    phone: '',
    faxNumber: '',
    websiteUrl: '',
    hasDifferentPaymentStubAddress: false,
    paymentStubAddress: {
      addressLine1: '',
      addressLine2: '',
      city: '',
      state: '',
      zipCode: '',
      country: 'India',
    },
    primaryContactName: 'Sender Chintalarayudu1',
    primaryContactEmail: 'chintalarayudu1@gmail.com',
    emailsSentThrough: 'message-service@sender.zoho-books.in',
    baseCurrency: 'INR - Indian Rupee (₹)',
    fiscalYear: 'April - March',
    reportBasis: 'Accrual',
    organizationLanguage: 'English',
    communicationLanguages: ['English'],
    timeZone: '(GMT +05:30) India Standard Time (Asia/Kolkata)',
    dateFormat: 'dd/MM/yyyy',
    companyId: 'CIN-522006-SSD',
    addressFormat: '${Organization.Name}\n${Organization.AddressLine1}\n${Organization.AddressLine2}\n${Organization.City} - ${Organization.ZipCode}, ${Organization.State}\n${Organization.Country}',
    additionalFields: [
      { id: 'f-1', label: 'GSTIN', value: '37AAAAA0000A1Z5' },
      { id: 'f-2', label: 'MSME Reg No', value: 'UDYAM-AP-05-0012345' },
    ],
  },

  branding: {
    primaryColor: '#2563eb',
    watermarkText: 'ORIGINAL COPY',
    headerLayout: 'Compact Modern',
  },
  customDomain: {
    domainName: 'billing.apexgrowth.com',
    sslActive: true,
    cnameVerified: true,
  },
  locations: [
    {
      id: 'loc-1',
      name: 'San Francisco HQ',
      code: 'SF-01',
      address: '100 Financial Center Blvd, San Francisco, CA 94111',
      isDefault: true,
    },
    {
      id: 'loc-2',
      name: 'Austin Regional Office',
      code: 'ATX-02',
      address: '400 Congress Ave, Austin, TX 78701',
      isDefault: false,
    },
  ],
  aiIntegration: {
    enabled: true,
    smartOcr: true,
    autoCategorize: true,
    apiKey: 'sk-genai-****************',
  },
  subscription: {
    plan: 'Enterprise Scale Plan',
    billingCycle: 'Annual (Renews Oct 2026)',
    invoicesUsed: 480,
    invoicesLimit: 10000,
    usersUsed: 4,
    usersLimit: 25,
  },
  users: [
    { id: 'usr-1', name: 'Alexander Wright', email: 'alex@apexgrowth.com', role: 'Super Admin', status: 'Active', lastActive: 'Just now' },
    { id: 'usr-2', name: 'Sophia Chen', email: 'sophia@apexgrowth.com', role: 'Senior Accountant', status: 'Active', lastActive: '2 hours ago' },
    { id: 'usr-3', name: 'Marcus Brody', email: 'marcus@apexgrowth.com', role: 'Project Manager', status: 'Active', lastActive: 'Yesterday' },
    { id: 'usr-4', name: 'Elena Rostova', email: 'elena@apexgrowth.com', role: 'Staff Auditor', status: 'Inactive', lastActive: '3 days ago' },
  ],
  roles: [
    { id: 'rol-1', name: 'Super Admin', description: 'Full system control, settings, billing, and audit logs', permissionsCount: 42 },
    { id: 'rol-2', name: 'Senior Accountant', description: 'Can post journal entries, approve bills, create invoices & reconcile', permissionsCount: 35 },
    { id: 'rol-3', name: 'Project Manager', description: 'Access to assigned projects, time logs, client estimates', permissionsCount: 18 },
    { id: 'rol-4', name: 'Auditor', description: 'Read-only access to General Ledger, Reports, and Tax records', permissionsCount: 12 },
  ],
  userPreferences: {
    theme: 'Light',
    language: 'English (US)',
    dateFormat: 'YYYY-MM-DD',
    timezone: 'America/Los_Angeles (PST)',
    currencyFormat: '$1,234,567.89',
  },
  taxRates: [
    { id: 'tax-1', name: 'Standard Sales Tax (8.5%)', rate: 8.5, code: 'TAX-STD', isCompound: false },
    { id: 'tax-2', name: 'GST 18%', rate: 18.0, code: 'GST-18', isCompound: false },
    { id: 'tax-3', name: 'Reduced VAT (5%)', rate: 5.0, code: 'VAT-5', isCompound: false },
    { id: 'tax-4', name: 'Exempt / Zero Tax', rate: 0.0, code: 'TAX-0', isCompound: false },
  ],
  directTaxes: {
    tdsEnabled: true,
    panNumber: 'AAAPA1234F',
    tanNumber: 'SFOA12345B',
    defaultTdsRate: 10.0,
  },
  msme: {
    isRegistered: true,
    udyamNumber: 'UDYAM-CA-01-0094821',
    category: 'Small',
    alert45Days: true,
  },
  generalConfig: {
    defaultBankAccountId: 'acc-1000',
    baseCurrency: 'USD',
    rounding: 'Round to nearest 0.01',
  },
  currencies: [
    { code: 'USD', symbol: '$', name: 'US Dollar', rate: 1.0, autoUpdate: false },
    { code: 'EUR', symbol: '€', name: 'Euro', rate: 0.92, autoUpdate: true },
    { code: 'GBP', symbol: '£', name: 'British Pound', rate: 0.78, autoUpdate: true },
    { code: 'INR', symbol: '₹', name: 'Indian Rupee', rate: 83.5, autoUpdate: true },
    { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar', rate: 1.35, autoUpdate: true },
  ],
  paymentTerms: [
    { id: 'pt-1', name: 'Due on Receipt', days: 0, isDefault: false },
    { id: 'pt-2', name: 'Net 15 Days', days: 15, isDefault: false },
    { id: 'pt-3', name: 'Net 30 Days', days: 30, isDefault: true },
    { id: 'pt-4', name: 'Net 60 Days', days: 60, isDefault: false },
  ],
  openingBalancesLocked: true,
  reminders: [
    { id: 'rem-1', name: 'Upcoming Due Date (3 Days Before)', daysBeforeOrAfter: 3, type: 'before', enabled: true, subject: 'Payment Reminder: Invoice {{invoice_number}} Due Soon' },
    { id: 'rem-2', name: 'Due Date Notification (On Due Date)', daysBeforeOrAfter: 0, type: 'before', enabled: true, subject: 'Invoice {{invoice_number}} is Due Today' },
    { id: 'rem-3', name: 'Overdue Alert (7 Days Overdue)', daysBeforeOrAfter: 7, type: 'after', enabled: true, subject: 'URGENT: Invoice {{invoice_number}} Overdue' },
  ],
  customerPortal: {
    enabled: true,
    allowPayOnline: true,
    allowAcceptEstimate: true,
    domain: 'portal.apexgrowth.com',
  },
  vendorPortal: {
    enabled: true,
    allowUploadBills: true,
    allowAcceptPO: true,
  },
  numberSeries: {
    invoicePrefix: 'INV-2026-',
    invoiceNext: 104,
    billPrefix: 'BILL-2026-',
    billNext: 82,
    estimatePrefix: 'EST-2026-',
    estimateNext: 45,
    creditNotePrefix: 'CN-2026-',
    creditNoteNext: 12,
  },
  pdfTemplate: {
    style: 'Modern',
    primaryColor: '#2563eb',
    footerTerms: 'Payment due within 30 days. Thank you for your business!',
    showLogo: true,
  },
  emailNotifications: {
    invoiceSentSubject: 'Invoice {{invoice_number}} from {{firm_name}}',
    invoiceSentBody: 'Dear {{client_name}},\n\nPlease find attached invoice {{invoice_number}} for {{total_amount}}.\n\nThank you for choosing {{firm_name}}.',
    paymentReceiptSubject: 'Payment Confirmation for Invoice {{invoice_number}}',
    paymentReceiptBody: 'Dear {{client_name}},\n\nWe have received your payment of {{paid_amount}}. Thank you!',
  },
  smsNotifications: {
    enabled: true,
    gatewayKey: 'tw_live_984128913',
    senderId: 'APEXBK',
    autoSmsOnPayment: true,
  },
  reportingTags: [
    { id: 'tag-1', category: 'Cost Center', name: 'Tech Consulting' },
    { id: 'tag-2', category: 'Cost Center', name: 'Design Services' },
    { id: 'tag-3', category: 'Department', name: 'Sales & Marketing' },
    { id: 'tag-4', category: 'Location', name: 'San Francisco Office' },
  ],
  webTabs: [
    { id: 'tab-1', title: 'PowerBI Financial Dashboard', url: 'https://app.powerbi.com' },
    { id: 'tab-2', title: 'CRM Client Sync', url: 'https://hubspot.com' },
  ],
  digitalSignature: {
    enabled: true,
    signerName: 'Alexander Wright',
    designation: 'Managing Director & CFO',
    signatureText: 'Digitally signed by Alexander Wright on behalf of Apex Growth Partners',
  },
  workflowRules: [
    { id: 'wf-1', name: 'High Expense Manager Alert', module: 'Expenses', trigger: 'Amount > $1,000', action: 'Send Email Notification', status: 'Active' },
    { id: 'wf-2', name: 'Auto-Send Invoice Receipt', module: 'Invoices', trigger: 'Payment Status == Paid', action: 'Send Email Receipt', status: 'Active' },
    { id: 'wf-3', name: 'Overdue Credit Hold', module: 'Clients', trigger: 'Overdue Days > 60', action: 'Mark Credit Hold', status: 'Inactive' },
  ],
  workflowLogs: [
    { id: 'log-1', ruleName: 'Auto-Send Invoice Receipt', triggerTime: '2026-07-25 14:32', status: 'Success', details: 'Sent receipt for INV-2026-102 to client@acme.com' },
    { id: 'log-2', ruleName: 'High Expense Manager Alert', triggerTime: '2026-07-24 09:15', status: 'Success', details: 'Alerted CFO for expense EXP-2026-042 ($2,400)' },
  ],
  customersVendorsSettings: {
    defaultPaymentTerms: 'Net 30',
    creditLimitWarning: 50000,
    duplicateCheck: true,
  },
  itemsSettings: {
    enableSku: true,
    valuationMethod: 'FIFO',
    lowStockAlert: 10,
  },
  accountantSettings: {
    lockBooksDate: '2025-12-31',
    strictCoaMode: true,
  },
  projectsSettings: {
    roundingMinutes: 15,
    defaultHourlyRate: 150,
  },
  timesheetSettings: {
    requireApproval: true,
    maxDailyHours: 12,
  },
  paymentGateways: {
    stripeKey: 'pk_live_51M...',
    stripeEnabled: true,
    paypalEmail: 'payments@apexgrowth.com',
    paypalEnabled: true,
    razorpayKey: 'rzp_live_89138',
    razorpayEnabled: false,
  },
  vendorPayouts: {
    achEnabled: true,
    wiseEnabled: true,
    autoBatchPayout: false,
  },
  quotesSettings: {
    autoConvertOnAccept: true,
    expiryDays: 30,
    termsNotice: 'This quote is valid for 30 days from date of issue.',
  },
  salesOrdersSettings: {
    enableSO: true,
    reserveStock: true,
  },
  deliveryChallansSettings: {
    dispatchWarehouse: 'San Francisco HQ Warehouse',
    requireVehicleNo: true,
  },
  invoicesSettings: {
    defaultDueDays: 30,
    lateFeePercent: 1.5,
    autoAttachPdf: true,
  },
  recurringInvoicesSettings: {
    scheduleTime: '08:00 AM PST',
    maxRetryCard: 3,
  },
  paymentsReceivedSettings: {
    autoApplyOldest: true,
    matchTolerance: 0.05,
  },
  creditNotesSettings: {
    autoApplyFutureInvoices: true,
  },
  expensesSettings: {
    approvalThreshold: 1000,
    requireReceipt: true,
  },
  purchaseOrdersSettings: {
    requirePOAbove: 500,
    autoCloseMatched: true,
  },
  billsSettings: {
    defaultDueDays: 30,
    detectDuplicateBill: true,
  },
  paymentsMadeSettings: {
    batchThreshold: 10000,
    sendPaymentAdvice: true,
  },
  vendorCreditsSettings: {
    autoApplyFutureBills: true,
  },
};

export const initialAccounts: Account[] = [
  {
    id: 'acc-1000',
    code: '1000',
    name: 'Operating Bank Account (Chase)',
    type: 'Asset',
    subType: 'Bank',
    description: 'Primary checking account for revenue and operational disbursements',
    balance: 142500,
    isSystemAccount: true,
  },
  {
    id: 'acc-1010',
    code: '1010',
    name: 'Petty Cash Ledger',
    type: 'Asset',
    subType: 'Cash',
    description: 'Cash reserve for day-to-day minor office expenses',
    balance: 1850,
    isSystemAccount: true,
  },
  {
    id: 'acc-1100',
    code: '1100',
    name: 'Accounts Receivable',
    type: 'Asset',
    subType: 'Accounts Receivable',
    description: 'Uncollected client invoices',
    balance: 38400,
    isSystemAccount: true,
  },
  {
    id: 'acc-1200',
    code: '1200',
    name: 'Inventory Reserve & Stock',
    type: 'Asset',
    subType: 'Inventory',
    description: 'Raw materials, plywood stock, and finished goods',
    balance: 15400,
  },
  {
    id: 'acc-1300',
    code: '1300',
    name: 'Computer Hardware & Office Equipment',
    type: 'Asset',
    subType: 'Fixed Assets',
    description: 'Workstations, servers, and office furniture',
    balance: 24000,
  },
  {
    id: 'acc-1400',
    code: '1400',
    name: 'Prepaid Expenses & Security Deposits',
    type: 'Asset',
    subType: 'Other Current Assets',
    description: 'Office rent deposit and annual prepaid subscriptions',
    balance: 5000,
  },
  {
    id: 'acc-1500',
    code: '1500',
    name: 'Long-term Investments & Trademarks',
    type: 'Asset',
    subType: 'Other Assets',
    description: 'Patents, security bonds, and long term reserves',
    balance: 12000,
  },

  // 2. Liabilities
  {
    id: 'acc-2000',
    code: '2000',
    name: 'Accounts Payable',
    type: 'Liability',
    subType: 'Accounts Payable',
    description: 'Outstanding vendor bills and contractor balances',
    balance: 12400,
    isSystemAccount: true,
  },
  {
    id: 'acc-2100',
    code: '2100',
    name: 'Corporate Credit Card (Amex)',
    type: 'Liability',
    subType: 'Credit Cards',
    description: 'Revolving corporate credit balance for team travel and tools',
    balance: 4200,
  },
  {
    id: 'acc-2200',
    code: '2200',
    name: 'Sales & State Tax Payable',
    type: 'Liability',
    subType: 'Taxes Payable',
    description: 'Accrued sales tax owed to state Authorities',
    balance: 3260,
    isSystemAccount: true,
  },
  {
    id: 'acc-2300',
    code: '2300',
    name: 'Payroll Withholding & Benefits Payable',
    type: 'Liability',
    subType: 'Payroll Liabilities',
    description: 'Employee tax withholdings and health insurance premiums',
    balance: 5100,
  },
  {
    id: 'acc-2400',
    code: '2400',
    name: 'Bank Working Capital Loan',
    type: 'Liability',
    subType: 'Loans',
    description: 'Term loan for equipment expansion',
    balance: 35000,
  },
  {
    id: 'acc-2500',
    code: '2500',
    name: 'Unearned Revenue / Client Retainers',
    type: 'Liability',
    subType: 'Other Liabilities',
    description: 'Prepaid retainers for ongoing client projects',
    balance: 15000,
  },

  // 3. Equity
  {
    id: 'acc-3000',
    code: '3000',
    name: "Owner's Paid-in Capital",
    type: 'Equity',
    subType: 'Capital',
    description: 'Initial invested partner capital',
    balance: 100000,
    isSystemAccount: true,
  },
  {
    id: 'acc-3100',
    code: '3100',
    name: 'Retained Earnings',
    type: 'Equity',
    subType: 'Retained Earnings',
    description: 'Accumulated profits retained in the firm',
    balance: 55000,
    isSystemAccount: true,
  },
  {
    id: 'acc-3200',
    code: '3200',
    name: "Owner's Drawings & Distributions",
    type: 'Equity',
    subType: 'Drawings',
    description: 'Partner dividend payouts and personal withdrawals',
    balance: 12000,
  },
  {
    id: 'acc-3300',
    code: '3300',
    name: 'Common Stock & Other Equity Reserves',
    type: 'Equity',
    subType: 'Other Equity',
    description: 'Additional capital reserves',
    balance: 10000,
  },

  // 4. Income
  {
    id: 'acc-4000',
    code: '4000',
    name: 'Software Sales & License Fees',
    type: 'Income',
    subType: 'Sales',
    description: 'Direct product software licenses & package sales',
    balance: 112000,
  },
  {
    id: 'acc-4100',
    code: '4100',
    name: 'Professional Consulting Services',
    type: 'Income',
    subType: 'Services',
    description: 'Advisory and technical implementation fees',
    balance: 185000,
  },
  {
    id: 'acc-4200',
    code: '4200',
    name: 'Late Payment & Ancillary Fees',
    type: 'Income',
    subType: 'Other Operating Income',
    description: 'Misc project service charges and late fees',
    balance: 3200,
  },

  // 5. Cost of Goods Sold
  {
    id: 'acc-5000',
    code: '5000',
    name: 'Subcontractors & Specialist Labor',
    type: 'Cost of Goods Sold',
    subType: 'Subcontractors',
    description: 'Direct billable third-party engineers & experts',
    balance: 34500,
  },
  {
    id: 'acc-5100',
    code: '5100',
    name: 'Ply Stock & Materials',
    type: 'Cost of Goods Sold',
    subType: 'Materials',
    description: 'Plywood raw materials & sheets category',
    balance: 18500,
    isParent: true,
    subCategory: 'Ply',
  },
  {
    id: 'acc-5110',
    code: '5110',
    name: '18mm Ply',
    type: 'Cost of Goods Sold',
    subType: 'Materials',
    description: '18mm Commercial & Marine grade plywood sheets',
    balance: 11200,
    parentId: 'acc-5100',
    parentName: 'Ply Stock & Materials',
    subCategory: 'Ply',
  },
  {
    id: 'acc-5120',
    code: '5120',
    name: '16mm Ply',
    type: 'Cost of Goods Sold',
    subType: 'Materials',
    description: '16mm Calibrated hardwood plywood sheets',
    balance: 4800,
    parentId: 'acc-5100',
    parentName: 'Ply Stock & Materials',
    subCategory: 'Ply',
  },
  {
    id: 'acc-5130',
    code: '5130',
    name: '12mm Ply',
    type: 'Cost of Goods Sold',
    subType: 'Materials',
    description: '12mm Backing & structural plywood sheets',
    balance: 2500,
    parentId: 'acc-5100',
    parentName: 'Ply Stock & Materials',
    subCategory: 'Ply',
  },
  {
    id: 'acc-5200',
    code: '5200',
    name: 'Direct Project Engineering Wages',
    type: 'Cost of Goods Sold',
    subType: 'Direct Labor',
    description: 'Billable engineering team salaries',
    balance: 42000,
  },
  {
    id: 'acc-5300',
    code: '5300',
    name: 'Server Hosting for Billable Apps',
    type: 'Cost of Goods Sold',
    subType: 'Other Direct Costs',
    description: 'AWS & Cloud SQL instances allocated per client project',
    balance: 6200,
  },

  // 6. Expenses
  {
    id: 'acc-6000',
    code: '6000',
    name: 'Executive & Admin Staff Salaries',
    type: 'Expense',
    subType: 'Payroll',
    description: 'Monthly staff salaries, health benefits, and payroll fees',
    balance: 48000,
  },
  {
    id: 'acc-6100',
    code: '6100',
    name: 'Office Stationery & Rent',
    type: 'Expense',
    subType: 'Office & Administrative',
    description: 'Monthly office lease and supplies',
    balance: 16200,
  },
  {
    id: 'acc-6200',
    code: '6200',
    name: 'Google Ads & Digital Marketing',
    type: 'Expense',
    subType: 'Sales & Marketing',
    description: 'Online campaigns, sponsorship, and brand promo',
    balance: 9500,
  },
  {
    id: 'acc-6300',
    code: '6300',
    name: 'Travel, Fuel & Client Entertainment',
    type: 'Expense',
    subType: 'Travel & Vehicle',
    description: 'Flights, lodging, meals for client meetings',
    balance: 4800,
  },
  {
    id: 'acc-6400',
    code: '6400',
    name: 'High-speed Internet & Phone Utilities',
    type: 'Expense',
    subType: 'Utilities & Communication',
    description: 'Fiber internet connection and VoIP lines',
    balance: 1800,
  },
  {
    id: 'acc-6500',
    code: '6500',
    name: 'Legal, Tax & Accounting Advisory',
    type: 'Expense',
    subType: 'Professional Services',
    description: 'Audit, legal retainers, and filing fees',
    balance: 3900,
  },
  {
    id: 'acc-6600',
    code: '6600',
    name: 'SaaS Tooling & Licenses',
    type: 'Expense',
    subType: 'Software & Subscriptions',
    description: 'Figma, GitHub, Slack, and Zoom subscriptions',
    balance: 8400,
  },
  {
    id: 'acc-6700',
    code: '6700',
    name: 'Equipment Maintenance & Hardware Repairs',
    type: 'Expense',
    subType: 'Repairs & Maintenance',
    description: 'IT repairs, server servicing, and workstation maintenance',
    balance: 2100,
  },
  {
    id: 'acc-6800',
    code: '6800',
    name: 'Merchant Processing & Bank Fees',
    type: 'Expense',
    subType: 'Financial Expenses',
    description: 'Stripe transaction fees and bank monthly charges',
    balance: 1250,
  },
  {
    id: 'acc-6900',
    code: '6900',
    name: 'Equipment Depreciation Expense',
    type: 'Expense',
    subType: 'Depreciation & Amortization',
    description: 'Annual scheduled depreciation for laptops and furniture',
    balance: 3600,
  },
  {
    id: 'acc-6950',
    code: '6950',
    name: 'General Sundry Expenses',
    type: 'Expense',
    subType: 'Miscellaneous Expenses',
    description: 'Other unclassified operational expenses',
    balance: 850,
  },

  // 7. Other Income
  {
    id: 'acc-7000',
    code: '7000',
    name: 'Bank Interest Income',
    type: 'Other Income',
    subType: 'Interest Income',
    description: 'Interest earned on high-yield treasury account',
    balance: 2400,
  },
  {
    id: 'acc-7100',
    code: '7100',
    name: 'Gain on Equipment Asset Sales',
    type: 'Other Income',
    subType: 'Asset Gains',
    description: 'Profit from selling old office workstations',
    balance: 1500,
  },

  // 8. Other Expense
  {
    id: 'acc-8000',
    code: '8000',
    name: 'Bank Loan Interest Expense',
    type: 'Other Expense',
    subType: 'Interest Expense',
    description: 'Interest payments on bank term loan',
    balance: 1800,
  },
  {
    id: 'acc-8100',
    code: '8100',
    name: 'Loss on Scrapped Asset Disposal',
    type: 'Other Expense',
    subType: 'Asset Losses',
    description: 'Loss from retired hardware assets',
    balance: 600,
  },
];

export const cleanInitialAccounts: Account[] = initialAccounts.map((acc) => ({
  ...acc,
  balance: 0,
}));


export const initialClients: Client[] = [
  {
    id: 'cli-101',
    name: 'AcroTech Solutions Inc.',
    companyName: 'AcroTech Solutions',
    email: 'finance@acrotech.io',
    phone: '+1 (415) 890-3320',
    billingAddress: '450 Tech Way, Floor 8, San Jose, CA 95110',
    taxId: 'US-92-104928',
    currency: 'USD',
    paymentTerms: 'Net 30',
    notes: 'Key enterprise SaaS client. Project billing on 15th and end of month.',
    createdAt: '2026-01-15',
  },
  {
    id: 'cli-102',
    name: 'Vanguard Health Systems',
    companyName: 'Vanguard Health',
    email: 'ap@vanguardhealth.org',
    phone: '+1 (312) 441-9011',
    billingAddress: '88 Healthcare Plaza, Chicago, IL 60611',
    taxId: 'US-36-881920',
    currency: 'USD',
    paymentTerms: 'Net 15',
    notes: 'Strict HIPAA compliance on all sub-contractors.',
    createdAt: '2026-02-01',
  },
  {
    id: 'cli-103',
    name: 'Urban Architecture Co',
    companyName: 'Urban Design & Build',
    email: 'accounts@urbandesign.com',
    phone: '+1 (206) 552-8840',
    billingAddress: '120 Pine St, Seattle, WA 98101',
    taxId: 'US-91-440219',
    currency: 'USD',
    paymentTerms: 'Due on Receipt',
    notes: 'Smart office building automation contract.',
    createdAt: '2026-03-10',
  },
  {
    id: 'cli-104',
    name: 'Nexus Digital Media',
    companyName: 'Nexus Media Corp',
    email: 'billing@nexusdigital.com',
    phone: '+1 (212) 701-4433',
    billingAddress: '350 Fifth Ave, New York, NY 10118',
    taxId: 'US-13-772910',
    currency: 'USD',
    paymentTerms: 'Net 30',
    createdAt: '2026-04-05',
  },
];

export const initialVendors: Vendor[] = [
  {
    id: 'ven-201',
    name: 'AWS Cloud Services',
    companyName: 'Amazon Web Services',
    email: 'billing@aws.amazon.com',
    phone: '+1 (800) 300-2971',
    taxId: 'US-41-085200',
    category: 'Cloud Infrastructure',
  },
  {
    id: 'ven-202',
    name: 'DevOps Experts LLC',
    companyName: 'DevOps Experts',
    email: 'contact@devopsexperts.com',
    phone: '+1 (415) 301-9922',
    taxId: 'US-94-332019',
    category: 'Subcontractors & Specialist Labor',
  },
  {
    id: 'ven-203',
    name: 'Metropolitan Real Estate',
    companyName: 'Metro Lease Mgmt',
    email: 'rent@metropolease.com',
    phone: '+1 (415) 220-1100',
    category: 'Office Rent & Utilities',
  },
];

export const initialProjects: Project[] = [
  {
    id: 'prj-1',
    code: 'PRJ-101',
    name: 'AcroTech Mobile App Redesign',
    clientId: 'cli-101',
    clientName: 'AcroTech Solutions Inc.',
    description: 'Complete UI/UX overhaul and native iOS/Android development with cloud backend sync.',
    status: 'Active',
    budgetType: 'Fixed Cost',
    totalBudget: 65000,
    hourlyRate: 150,
    startDate: '2026-02-01',
    endDate: '2026-08-30',
    manager: 'Sarah Jenkins (Senior Partner)',
    createdAt: '2026-01-20',
  },
  {
    id: 'prj-2',
    code: 'PRJ-102',
    name: 'Vanguard EHR Systems Integration',
    clientId: 'cli-102',
    clientName: 'Vanguard Health Systems',
    description: 'HL7/FHIR compliant patient data pipeline and automated analytics dashboard.',
    status: 'Active',
    budgetType: 'Time & Materials',
    totalBudget: 85000,
    hourlyRate: 175,
    startDate: '2026-03-01',
    endDate: '2026-10-15',
    manager: 'David Chen (Technical Architect)',
    createdAt: '2026-02-25',
  },
  {
    id: 'prj-3',
    code: 'PRJ-103',
    name: 'Urban Smart Office Automation',
    clientId: 'cli-103',
    clientName: 'Urban Architecture Co',
    description: 'IoT sensor network deployment, energy metering, and occupancy analytics.',
    status: 'Active',
    budgetType: 'Fixed Cost',
    totalBudget: 42000,
    hourlyRate: 140,
    startDate: '2026-04-10',
    manager: 'Elena Rostova (IoT Lead)',
    createdAt: '2026-04-01',
  },
  {
    id: 'prj-4',
    code: 'PRJ-104',
    name: 'Nexus Cloud Infrastructure Migration',
    clientId: 'cli-104',
    clientName: 'Nexus Digital Media',
    description: 'Migration from legacy dedicated host to Kubernetes on AWS with automated CI/CD.',
    status: 'Completed',
    budgetType: 'Time & Materials',
    totalBudget: 35000,
    hourlyRate: 160,
    startDate: '2026-01-10',
    endDate: '2026-05-15',
    manager: 'David Chen',
    createdAt: '2026-01-05',
  },
];

export const initialTimeEntries: TimeEntry[] = [
  {
    id: 'time-1',
    projectId: 'prj-1',
    projectName: 'AcroTech Mobile App Redesign',
    clientName: 'AcroTech Solutions Inc.',
    staffName: 'Sarah Jenkins',
    taskName: 'UI Wireframing & User Journey Design',
    date: '2026-07-10',
    hours: 12,
    hourlyRate: 150,
    isBillable: true,
    isBilled: true,
    invoiceId: 'inv-1001',
    description: 'Figma wireframes review session with AcroTech executive team',
  },
  {
    id: 'time-2',
    projectId: 'prj-1',
    projectName: 'AcroTech Mobile App Redesign',
    clientName: 'AcroTech Solutions Inc.',
    staffName: 'Marcus Vance',
    taskName: 'React Native Component Architecture',
    date: '2026-07-18',
    hours: 24,
    hourlyRate: 150,
    isBillable: true,
    isBilled: false,
    description: 'State management setup and biometric login module implementation',
  },
  {
    id: 'time-3',
    projectId: 'prj-2',
    projectName: 'Vanguard EHR Systems Integration',
    clientName: 'Vanguard Health Systems',
    staffName: 'David Chen',
    taskName: 'FHIR API Endpoint Mapping',
    date: '2026-07-15',
    hours: 18,
    hourlyRate: 175,
    isBillable: true,
    isBilled: true,
    invoiceId: 'inv-1002',
    description: 'Patient records synchronization pipeline and encryption layer',
  },
  {
    id: 'time-4',
    projectId: 'prj-2',
    projectName: 'Vanguard EHR Systems Integration',
    clientName: 'Vanguard Health Systems',
    staffName: 'Elena Rostova',
    taskName: 'Security Audit & Compliance Testing',
    date: '2026-07-22',
    hours: 10,
    hourlyRate: 175,
    isBillable: true,
    isBilled: false,
    description: 'HIPAA vulnerability scan and access log auditing',
  },
  {
    id: 'time-5',
    projectId: 'prj-3',
    projectName: 'Urban Smart Office Automation',
    clientName: 'Urban Architecture Co',
    staffName: 'Elena Rostova',
    taskName: 'BACnet Protocol Integration',
    date: '2026-07-12',
    hours: 15,
    hourlyRate: 140,
    isBillable: true,
    isBilled: false,
    description: 'HVAC sensor telemetry calibration and cloud gateway test',
  },
];

export const initialInvoices: Invoice[] = [
  {
    id: 'inv-1001',
    invoiceNumber: 'INV-2026-001',
    clientId: 'cli-101',
    clientName: 'AcroTech Solutions Inc.',
    clientEmail: 'finance@acrotech.io',
    projectId: 'prj-1',
    projectName: 'AcroTech Mobile App Redesign',
    issueDate: '2026-07-01',
    dueDate: '2026-07-31',
    items: [
      {
        id: 'item-1',
        description: 'Phase 1 Milestone - UX Architecture & Prototype',
        accountId: 'acc-4100',
        quantity: 1,
        unitPrice: 25000,
        taxRate: 8.5,
        amount: 25000,
      },
      {
        id: 'item-2',
        description: 'Design Systems Lead Hours (12 hrs @ $150/hr)',
        accountId: 'acc-4000',
        quantity: 12,
        unitPrice: 150,
        taxRate: 8.5,
        amount: 1800,
      },
    ],
    subtotal: 26800,
    taxTotal: 2278,
    discount: 0,
    totalAmount: 29078,
    paidAmount: 29078,
    balanceDue: 0,
    status: 'Paid',
    notes: 'Thank you for your business. Payment received via Wire Transfer.',
    terms: 'Net 30. 1.5% monthly late fee applies to overdue balances.',
    createdAt: '2026-07-01',
  },
  {
    id: 'inv-1002',
    invoiceNumber: 'INV-2026-002',
    clientId: 'cli-102',
    clientName: 'Vanguard Health Systems',
    clientEmail: 'ap@vanguardhealth.org',
    projectId: 'prj-2',
    projectName: 'Vanguard EHR Systems Integration',
    issueDate: '2026-07-15',
    dueDate: '2026-07-30',
    items: [
      {
        id: 'item-3',
        description: 'FHIR Integration Consulting (18 hrs @ $175/hr)',
        accountId: 'acc-4000',
        quantity: 18,
        unitPrice: 175,
        taxRate: 0,
        amount: 3150,
      },
      {
        id: 'item-4',
        description: 'Data Pipeline Architecture Setup Milestone',
        accountId: 'acc-4100',
        quantity: 1,
        unitPrice: 18000,
        taxRate: 0,
        amount: 18000,
      },
    ],
    subtotal: 21150,
    taxTotal: 0,
    discount: 500,
    totalAmount: 20650,
    paidAmount: 0,
    balanceDue: 20650,
    status: 'Sent',
    notes: 'Please reference INV-2026-002 on ACH payments.',
    terms: 'Net 15.',
    createdAt: '2026-07-15',
  },
  {
    id: 'inv-1003',
    invoiceNumber: 'INV-2026-003',
    clientId: 'cli-103',
    clientName: 'Urban Architecture Co',
    clientEmail: 'accounts@urbandesign.com',
    projectId: 'prj-3',
    projectName: 'Urban Smart Office Automation',
    issueDate: '2026-06-15',
    dueDate: '2026-06-15',
    items: [
      {
        id: 'item-5',
        description: 'Initial Equipment Procurement Retainer Deposit',
        accountId: 'acc-4100',
        quantity: 1,
        unitPrice: 15000,
        taxRate: 8.5,
        amount: 15000,
      },
    ],
    subtotal: 15000,
    taxTotal: 1275,
    discount: 0,
    totalAmount: 16275,
    paidAmount: 0,
    balanceDue: 16275,
    status: 'Overdue',
    notes: 'Payment required before on-site hardware deployment.',
    terms: 'Due on Receipt.',
    createdAt: '2026-06-15',
  },
  {
    id: 'inv-1004',
    invoiceNumber: 'INV-2026-004',
    clientId: 'cli-104',
    clientName: 'Nexus Digital Media',
    clientEmail: 'billing@nexusdigital.com',
    projectId: 'prj-4',
    projectName: 'Nexus Cloud Infrastructure Migration',
    issueDate: '2026-05-15',
    dueDate: '2026-06-15',
    items: [
      {
        id: 'item-6',
        description: 'Final Project Delivery & Migration Handoff',
        accountId: 'acc-4100',
        quantity: 1,
        unitPrice: 35000,
        taxRate: 0,
        amount: 35000,
      },
    ],
    subtotal: 35000,
    taxTotal: 0,
    discount: 0,
    totalAmount: 35000,
    paidAmount: 35000,
    balanceDue: 0,
    status: 'Paid',
    createdAt: '2026-05-15',
  },
];

export const initialEstimates: Estimate[] = [
  {
    id: 'est-2001',
    estimateNumber: 'EST-2026-001',
    clientId: 'cli-101',
    clientName: 'AcroTech Solutions Inc.',
    projectId: 'prj-1',
    issueDate: '2026-07-20',
    expiryDate: '2026-08-20',
    items: [
      {
        id: 'eitem-1',
        description: 'Phase 2 - Payment Gateway & Subscriptions Engine',
        accountId: 'acc-4100',
        quantity: 1,
        unitPrice: 28000,
        taxRate: 8.5,
        amount: 28000,
      },
    ],
    subtotal: 28000,
    taxTotal: 2380,
    totalAmount: 30380,
    status: 'Sent',
    notes: 'Estimate valid for 30 days from date of issuance.',
    createdAt: '2026-07-20',
  },
];

export const initialExpenses: Expense[] = [
  {
    id: 'exp-501',
    referenceNumber: 'EXP-2026-012',
    vendorId: 'ven-202',
    vendorName: 'DevOps Experts LLC',
    accountId: 'acc-5000',
    accountName: 'Subcontractors & Specialist Labor',
    paidFromAccountId: 'acc-1000',
    projectId: 'prj-1',
    projectName: 'AcroTech Mobile App Redesign',
    clientId: 'cli-101',
    date: '2026-07-05',
    amount: 6400,
    taxAmount: 0,
    isBillable: true,
    isBilled: true,
    paymentStatus: 'Paid',
    description: 'Senior iOS developer contracting services (40 hrs @ $160/hr)',
    createdAt: '2026-07-05',
  },
  {
    id: 'exp-502',
    referenceNumber: 'EXP-2026-013',
    vendorId: 'ven-201',
    vendorName: 'AWS Cloud Services',
    accountId: 'acc-6000',
    accountName: 'Cloud Infrastructure & SaaS Software',
    paidFromAccountId: 'acc-1000',
    projectId: 'prj-2',
    projectName: 'Vanguard EHR Systems Integration',
    clientId: 'cli-102',
    date: '2026-07-10',
    amount: 1450,
    taxAmount: 0,
    isBillable: false,
    paymentStatus: 'Paid',
    description: 'Dedicated staging cluster for FHIR API testing',
    createdAt: '2026-07-10',
  },
  {
    id: 'exp-503',
    referenceNumber: 'EXP-2026-014',
    vendorId: 'ven-203',
    vendorName: 'Metropolitan Real Estate',
    accountId: 'acc-6100',
    accountName: 'Office Rent & Utilities',
    paidFromAccountId: 'acc-1000',
    date: '2026-07-01',
    amount: 4200,
    taxAmount: 0,
    isBillable: false,
    paymentStatus: 'Paid',
    description: 'Monthly office suite lease payment',
    createdAt: '2026-07-01',
  },
  {
    id: 'exp-504',
    referenceNumber: 'EXP-2026-015',
    accountId: 'acc-6200',
    accountName: 'Travel & Client Entertainment',
    paidFromAccountId: 'acc-1010',
    projectId: 'prj-3',
    projectName: 'Urban Smart Office Automation',
    clientId: 'cli-103',
    date: '2026-07-14',
    amount: 380,
    taxAmount: 0,
    isBillable: true,
    isBilled: false,
    paymentStatus: 'Paid',
    description: 'On-site engineering site survey flight and taxi expense',
    createdAt: '2026-07-14',
  },
];

export const initialJournalEntries: JournalEntry[] = [
  {
    id: 'jrn-1',
    entryNumber: 'JRN-2026-001',
    date: '2026-07-01',
    reference: 'Capital Contribution',
    description: 'Partner equity infusion into operating bank account',
    lines: [
      {
        id: 'jl-1',
        accountId: 'acc-1000',
        accountCode: '1000',
        accountName: 'Operating Bank Account (Chase)',
        debit: 50000,
        credit: 0,
      },
      {
        id: 'jl-2',
        accountId: 'acc-3000',
        accountCode: '3000',
        accountName: "Owner's Capital",
        debit: 0,
        credit: 50000,
      },
    ],
    status: 'Posted',
    createdAt: '2026-07-01',
  },
  {
    id: 'jrn-2',
    entryNumber: 'JRN-2026-002',
    date: '2026-07-15',
    reference: 'Prepaid Software License',
    description: 'Annual enterprise SaaS tooling allocation',
    lines: [
      {
        id: 'jl-3',
        accountId: 'acc-6000',
        accountCode: '6000',
        accountName: 'Cloud Infrastructure & SaaS Software',
        debit: 2400,
        credit: 0,
      },
      {
        id: 'jl-4',
        accountId: 'acc-1000',
        accountCode: '1000',
        accountName: 'Operating Bank Account (Chase)',
        debit: 0,
        credit: 2400,
      },
    ],
    status: 'Posted',
    createdAt: '2026-07-15',
  },
];

export const initialSalesOrders = [
  {
    id: 'so-101',
    orderNumber: 'SO-2026-001',
    clientName: 'Acme Tech Solutions',
    orderDate: '2026-07-15',
    expectedDeliveryDate: '2026-08-01',
    totalAmount: 18500,
    status: 'In Production' as const,
    notes: 'Custom hardware integration & cloud setup',
  },
  {
    id: 'so-102',
    orderNumber: 'SO-2026-002',
    clientName: 'Global Enterprise Corp',
    orderDate: '2026-07-18',
    expectedDeliveryDate: '2026-07-28',
    totalAmount: 42000,
    status: 'Shipped' as const,
    notes: 'Batch delivery with serial inspection',
  },
  {
    id: 'so-103',
    orderNumber: 'SO-2026-003',
    clientName: 'Acme Tech Solutions',
    orderDate: '2026-07-20',
    expectedDeliveryDate: '2026-08-10',
    totalAmount: 9500,
    status: 'Confirmed' as const,
    notes: 'Awaiting manufacturing completion',
  },
];

export const initialDeliveryChallans = [
  {
    id: 'dc-1',
    challanNumber: 'DC-2026-001',
    clientName: 'Acme Tech Solutions',
    dispatchDate: '2026-07-22',
    deliveryAddress: 'Building A, Silicon Valley Tech Park, CA',
    itemsSummary: '10x Rack Servers, 25x Switches, 50x Patch Cables',
    status: 'Delivered' as const,
  },
  {
    id: 'dc-2',
    challanNumber: 'DC-2026-002',
    clientName: 'Global Enterprise Corp',
    dispatchDate: '2026-07-26',
    deliveryAddress: 'Suite 400, Financial District, NY',
    itemsSummary: '5x Enterprise Workstations & Dual Monitors',
    status: 'In Transit' as const,
  },
];

export const initialCreditNotes = [
  {
    id: 'cn-1',
    cnNumber: 'CN-2026-001',
    clientName: 'Acme Tech Solutions',
    originalInvoiceNumber: 'INV-2026-001',
    issueDate: '2026-07-21',
    totalAmount: 1200,
    remainingAmount: 1200,
    status: 'Open' as const,
    reason: 'SLA downtime credit memo',
  },
];

export const initialPaymentsReceived = [
  {
    id: 'pr-1',
    paymentNumber: 'REC-2026-001',
    clientName: 'Acme Tech Solutions',
    invoiceNumber: 'INV-2026-001',
    paymentDate: '2026-07-20',
    paymentMethod: 'Bank Wire Transfer',
    referenceNumber: 'TXN-99881122',
    amount: 12500,
  },
  {
    id: 'pr-2',
    paymentNumber: 'REC-2026-002',
    clientName: 'Global Enterprise Corp',
    invoiceNumber: 'INV-2026-002',
    paymentDate: '2026-07-25',
    paymentMethod: 'Credit Card / Stripe',
    referenceNumber: 'CH-77443311',
    amount: 8400,
  },
];

export const initialRecurringInvoices = [
  {
    id: 'rec-1',
    profileName: 'Monthly Retainer - Tech Retainer',
    clientName: 'Acme Tech Solutions',
    frequency: 'Monthly' as const,
    amount: 4500,
    nextRunDate: '2026-08-01',
    status: 'Active' as const,
    autoSend: true,
  },
  {
    id: 'rec-2',
    profileName: 'Quarterly Maintenance & Audits',
    clientName: 'Global Enterprise Corp',
    frequency: 'Quarterly' as const,
    amount: 12000,
    nextRunDate: '2026-09-15',
    status: 'Active' as const,
    autoSend: false,
  },
];

export const initialPurchaseOrders = [
  {
    id: 'po-1',
    poNumber: 'PO-2026-001',
    vendorName: 'AWS Cloud Services',
    orderDate: '2026-07-15',
    expectedDate: '2026-07-30',
    totalAmount: 18400,
    status: 'Issued' as const,
    notes: 'Enterprise server hardware procurement',
  },
  {
    id: 'po-2',
    poNumber: 'PO-2026-002',
    vendorName: 'Dell Hardware Direct',
    orderDate: '2026-07-18',
    expectedDate: '2026-08-05',
    totalAmount: 10000,
    status: 'Pending Receipt' as const,
    notes: 'Monitors & accessories batch',
  },
];

export const initialBills = [
  {
    id: 'bill-1',
    billNumber: 'BILL-2026-001',
    vendorName: 'AWS Cloud Services',
    billDate: '2026-07-10',
    dueDate: '2026-08-10',
    totalAmount: 14500,
    amountPaid: 0,
    status: 'Unpaid' as const,
    notes: 'Monthly Cloud Infrastructure invoice',
  },
  {
    id: 'bill-2',
    billNumber: 'BILL-2026-002',
    vendorName: 'Dell Hardware Direct',
    billDate: '2026-06-15',
    dueDate: '2026-07-15',
    totalAmount: 8200,
    amountPaid: 8200,
    status: 'Paid' as const,
    notes: 'Office monitor upgrade batch',
  },
];

export const initialRecurringBills = [
  {
    id: 'rec-bill-1',
    profileName: 'HQ Office Commercial Lease Rent',
    vendorName: 'Metropolitan Real Estate Trust',
    frequency: 'Monthly' as const,
    amount: 8500,
    nextBillDate: '2026-08-01',
    status: 'Active' as const,
  },
  {
    id: 'rec-bill-2',
    profileName: 'Quarterly Corporate Insurance Policy',
    vendorName: 'Global Shield Insurance',
    frequency: 'Quarterly' as const,
    amount: 4200,
    nextBillDate: '2026-10-01',
    status: 'Active' as const,
  },
];

export const initialVendorCredits = [
  {
    id: 'vc-1',
    creditNoteNumber: 'VCR-2026-001',
    vendorName: 'AWS Cloud Services',
    billNumber: 'BILL-2026-001',
    issueDate: '2026-07-20',
    creditAmount: 1200,
    remainingAmount: 1200,
    status: 'Open' as const,
    notes: 'SLA Uptime Credit Adjustment',
  },
  {
    id: 'vc-2',
    creditNoteNumber: 'VCR-2026-002',
    vendorName: 'Dell Hardware Direct',
    billNumber: 'BILL-2026-002',
    issueDate: '2026-07-05',
    creditAmount: 500,
    remainingAmount: 0,
    status: 'Fully Applied' as const,
    notes: 'Damaged packaging return credit',
  },
];

export const initialPaymentsMade = [
  {
    id: 'pm-1',
    paymentNumber: 'PAY-2026-001',
    vendorName: 'AWS Cloud Services',
    billNumber: 'BILL-2026-001',
    paymentDate: '2026-07-12',
    paymentMethod: 'Bank Wire Transfer',
    referenceNumber: 'REF-884422',
    amount: 14500,
  },
  {
    id: 'pm-2',
    paymentNumber: 'PAY-2026-002',
    vendorName: 'Dell Hardware Direct',
    billNumber: 'BILL-2026-002',
    paymentDate: '2026-07-16',
    paymentMethod: 'Corporate Credit Card',
    referenceNumber: 'CC-991100',
    amount: 8200,
  },
];

export const initialRecurringExpenses = [
  {
    id: 'rec-exp-1',
    profileName: 'AWS Infrastructure Monthly Hosting',
    vendorName: 'AWS Cloud Services',
    category: 'Hosting & Server Infrastructure',
    frequency: 'Monthly' as const,
    amount: 1450,
    nextRunDate: '2026-08-01',
    status: 'Active' as const,
  },
  {
    id: 'rec-exp-2',
    profileName: 'Office Internet & Fiber Subscription',
    vendorName: 'Comcast Business',
    category: 'Utilities & Internet',
    frequency: 'Monthly' as const,
    amount: 320,
    nextRunDate: '2026-08-05',
    status: 'Active' as const,
  },
  {
    id: 'rec-exp-3',
    profileName: 'GitHub Enterprise Team Licenses',
    vendorName: 'GitHub Inc',
    category: 'Software & Subscriptions',
    frequency: 'Yearly' as const,
    amount: 2500,
    nextRunDate: '2026-11-15',
    status: 'Active' as const,
  },
];

