import React, { useEffect, useMemo, useState } from 'react';
import { Plus, RefreshCw, RotateCcw, X } from 'lucide-react';
import { apiClient } from '../../api/client';
import { useBooks } from '../../context/BooksContext';
import { formatCurrency, formatDate } from '../../utils/formatters';

interface AssetRow { id: string; asset_code: string; name: string; asset_category: string; purchase_date: string; purchase_value: number; accumulated_depreciation: number; net_book_value: number; status: string; }
const today = () => new Date().toISOString().slice(0, 10);

export const FixedAssetsView: React.FC = () => {
  const { accounts, settings } = useBooks();
  const [assets, setAssets] = useState<AssetRow[]>([]);
  const [selected, setSelected] = useState<AssetRow | null>(null);
  const [open, setOpen] = useState(false);
  const [error, setError] = useState('');
  const [periodKey, setPeriodKey] = useState(today().slice(0, 7));
  const [reason, setReason] = useState('Correcting the selected asset lifecycle entry');
  const [form, setForm] = useState({ assetCode: '', name: '', assetCategory: 'Equipment', purchaseDate: today(), inServiceDate: today(), purchaseValue: '', residualValue: '0', usefulLifeMonths: '60', assetAccountId: '', accumulatedDepreciationAccountId: '', depreciationExpenseAccountId: '' });
  const fixedAccounts = useMemo(() => accounts.filter(a => a.type === 'Asset' && a.status !== 'Inactive'), [accounts]);
  const expenseAccounts = useMemo(() => accounts.filter(a => a.type === 'Expense' && a.status !== 'Inactive'), [accounts]);
  const bankAccounts = useMemo(() => fixedAccounts.filter(a => ['Bank', 'Cash', 'Cash & Bank', 'Digital Wallet'].includes(a.subType)), [fixedAccounts]);

  const load = async () => { const response = await apiClient.get<AssetRow[]>('/finance/fixed-assets'); if (response.error) setError(response.error); else { setAssets(response.data || []); setError(''); } };
  useEffect(() => { void load(); }, []);
  useEffect(() => { setForm(value => ({ ...value, assetAccountId: value.assetAccountId || fixedAccounts[0]?.id || '', accumulatedDepreciationAccountId: value.accumulatedDepreciationAccountId || fixedAccounts[0]?.id || '', depreciationExpenseAccountId: value.depreciationExpenseAccountId || expenseAccounts[0]?.id || '' })); }, [fixedAccounts, expenseAccounts]);
  const mutate = async (path: string, body: unknown) => { const response = await apiClient.post(path, body); if (response.error) setError(response.error); else { setSelected(null); await load(); } };
  const create = async (event: React.FormEvent) => { event.preventDefault(); const response = await apiClient.post('/finance/fixed-assets', { ...form, purchaseValue: Number(form.purchaseValue), residualValue: Number(form.residualValue), usefulLifeMonths: Number(form.usefulLifeMonths) }); if (response.error) setError(response.error); else { setOpen(false); await load(); } };

  return <div className="mx-auto max-w-7xl space-y-5 p-4 sm:p-6">
    <header className="flex items-center justify-between border-b border-slate-200 pb-4 dark:border-slate-800"><div><h2 className="text-xl font-semibold">Fixed Assets</h2><p className="mt-1 text-xs text-slate-500">Asset register, depreciation, disposal, and reversals</p></div><div className="flex gap-2"><button title="Refresh" onClick={() => void load()} className="grid h-9 w-9 place-items-center rounded-md border border-slate-300"><RefreshCw className="h-4 w-4" /></button><button onClick={() => setOpen(true)} className="inline-flex items-center gap-2 rounded-md bg-blue-600 px-3 py-2 text-xs font-semibold text-white"><Plus className="h-4 w-4" />New Asset</button></div></header>
    {error && <div className="border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <div className="overflow-x-auto border border-slate-200 dark:border-slate-800"><table className="w-full min-w-[800px] text-left text-xs"><thead className="bg-slate-50 text-slate-500 dark:bg-slate-950"><tr><th className="p-3">Asset</th><th className="p-3">Category</th><th className="p-3">Purchased</th><th className="p-3 text-right">Cost</th><th className="p-3 text-right">Accumulated</th><th className="p-3 text-right">Net book value</th><th className="p-3">Status</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{assets.map(asset => <tr key={asset.id} onClick={() => setSelected(asset)} className="cursor-pointer hover:bg-slate-50 dark:hover:bg-slate-900"><td className="p-3"><div className="font-semibold">{asset.name}</div><div className="font-financial text-slate-500">{asset.asset_code}</div></td><td className="p-3">{asset.asset_category}</td><td className="p-3">{formatDate(asset.purchase_date)}</td><td className="p-3 text-right font-financial">{formatCurrency(asset.purchase_value, settings.currencySymbol)}</td><td className="p-3 text-right font-financial">{formatCurrency(asset.accumulated_depreciation, settings.currencySymbol)}</td><td className="p-3 text-right font-financial font-semibold">{formatCurrency(asset.net_book_value, settings.currencySymbol)}</td><td className="p-3">{asset.status}</td></tr>)}{assets.length === 0 && <tr><td colSpan={7} className="p-10 text-center text-sm text-slate-500">No fixed assets</td></tr>}</tbody></table></div>
    {selected && <section className="border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between"><div><h3 className="font-semibold">{selected.name}</h3><p className="text-xs text-slate-500">{selected.asset_code}</p></div><button title="Close" onClick={() => setSelected(null)} className="grid h-8 w-8 place-items-center rounded-md"><X className="h-4 w-4" /></button></div><div className="mt-4 grid gap-3 sm:grid-cols-[160px_1fr_auto]"><input type="month" value={periodKey} onChange={e => setPeriodKey(e.target.value)} className="rounded-md border border-slate-300 p-2 text-sm" /><input value={reason} onChange={e => setReason(e.target.value)} className="rounded-md border border-slate-300 p-2 text-sm" /><div className="flex flex-wrap gap-2">{selected.status === 'ACTIVE' && <><button onClick={() => void mutate(`/finance/fixed-assets/${selected.id}/depreciate`, { periodKey })} className="rounded-md bg-blue-600 px-3 py-2 text-xs font-semibold text-white">Post Depreciation</button><button onClick={() => void mutate(`/finance/fixed-assets/${selected.id}/depreciation/reverse`, { periodKey, reason, reversalDate: today() })} className="inline-flex items-center gap-1 rounded-md border border-slate-300 px-3 py-2 text-xs font-semibold"><RotateCcw className="h-3.5 w-3.5" />Reverse</button><button disabled={!bankAccounts[0] || !expenseAccounts[0]} onClick={() => void mutate(`/finance/fixed-assets/${selected.id}/dispose`, { disposalDate: today(), saleProceeds: 0, proceedsBankAccountId: bankAccounts[0]?.id, gainLossAccountId: expenseAccounts[0]?.id })} className="rounded-md border border-red-300 px-3 py-2 text-xs font-semibold text-red-700">Dispose</button></>}{selected.status === 'DISPOSED' && <button onClick={() => void mutate(`/finance/fixed-assets/${selected.id}/disposal/reverse`, { reason, reversalDate: today() })} className="rounded-md border border-slate-300 px-3 py-2 text-xs font-semibold">Reverse Disposal</button>}</div></div></section>}
    {open && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 p-4"><form onSubmit={create} className="max-h-[90vh] w-full max-w-2xl space-y-4 overflow-y-auto rounded-lg bg-white p-5 shadow-xl dark:bg-slate-900"><div className="flex items-center justify-between"><h3 className="font-semibold">New Fixed Asset</h3><button type="button" title="Close" onClick={() => setOpen(false)}><X className="h-4 w-4" /></button></div><div className="grid gap-3 sm:grid-cols-2">{(['assetCode','name','assetCategory','purchaseValue','residualValue','usefulLifeMonths'] as const).map(key => <label key={key} className="text-xs font-semibold">{key.replace(/([A-Z])/g, ' $1')}<input type={['purchaseValue','residualValue','usefulLifeMonths'].includes(key) ? 'number' : 'text'} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} required className="mt-1 w-full rounded-md border border-slate-300 p-2 text-sm" /></label>)}<label className="text-xs font-semibold">Purchase date<input type="date" value={form.purchaseDate} onChange={e => setForm({...form,purchaseDate:e.target.value})} className="mt-1 w-full rounded-md border border-slate-300 p-2 text-sm" /></label><label className="text-xs font-semibold">In service date<input type="date" value={form.inServiceDate} onChange={e => setForm({...form,inServiceDate:e.target.value})} className="mt-1 w-full rounded-md border border-slate-300 p-2 text-sm" /></label>{([['assetAccountId','Asset account',fixedAccounts],['accumulatedDepreciationAccountId','Accumulated depreciation',fixedAccounts],['depreciationExpenseAccountId','Depreciation expense',expenseAccounts]] as const).map(([key,label,options]) => <label key={key} className="text-xs font-semibold">{label}<select value={form[key]} onChange={e => setForm({...form,[key]:e.target.value})} className="mt-1 w-full rounded-md border border-slate-300 p-2 text-sm">{options.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label>)}</div><div className="flex justify-end gap-2"><button type="button" onClick={() => setOpen(false)} className="rounded-md border border-slate-300 px-3 py-2 text-xs font-semibold">Cancel</button><button className="rounded-md bg-blue-600 px-3 py-2 text-xs font-semibold text-white">Create Asset</button></div></form></div>}
  </div>;
};
