import React, { useEffect, useState } from 'react';
import { CheckCircle2, CircleAlert, LockKeyhole, RotateCcw } from 'lucide-react';
import { apiClient } from '../../api/client';

interface CloseCheck { code: string; title: string; severity: string; passed: boolean; message: string; }
interface CloseStatus { periodKey: string; status: string; checks: CloseCheck[]; canClose: boolean; blockingFailuresCount: number; warningsCount: number; }
function range(periodKey: string) { const [year, month] = periodKey.split('-').map(Number); const end = new Date(Date.UTC(year, month, 0)).getUTCDate(); return { periodStart: `${periodKey}-01`, periodEnd: `${periodKey}-${String(end).padStart(2, '0')}` }; }

export const PeriodCloseView: React.FC = () => {
  const [periodKey, setPeriodKey] = useState(new Date().toISOString().slice(0, 7));
  const [status, setStatus] = useState<CloseStatus | null>(null);
  const [reason, setReason] = useState('Reopening period to post an approved correction');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const validate = async () => { const dates = range(periodKey); const response = await apiClient.get<CloseStatus>(`/finance/period-close/validate?periodKey=${periodKey}&periodStart=${dates.periodStart}&periodEnd=${dates.periodEnd}`); if (response.error) setError(response.error); else { setStatus(response.data); setError(''); } };
  useEffect(() => { void validate(); }, [periodKey]);
  const close = async () => { setBusy(true); const response = await apiClient.post('/finance/period-close/close', { periodKey, ...range(periodKey) }); setBusy(false); if (response.error) setError(response.error); else await validate(); };
  const reopen = async () => { setBusy(true); const response = await apiClient.post('/finance/period-close/reopen', { periodKey, reason }); setBusy(false); if (response.error) setError(response.error); else await validate(); };
  return <div className="mx-auto max-w-5xl space-y-6 p-4 sm:p-6"><header className="flex flex-wrap items-end justify-between gap-3 border-b border-slate-200 pb-4 dark:border-slate-800"><div><h2 className="text-xl font-semibold">Period Close</h2><p className="mt-1 text-xs text-slate-500">Integrity checks, locking evidence, and controlled reopen</p></div><label className="text-xs font-semibold">Accounting period<input type="month" value={periodKey} onChange={e => setPeriodKey(e.target.value)} className="mt-1 block rounded-md border border-slate-300 p-2 text-sm dark:border-slate-700 dark:bg-slate-900" /></label></header>{error && <div className="border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{status && <><div className="grid gap-px overflow-hidden border border-slate-200 bg-slate-200 sm:grid-cols-3 dark:border-slate-800 dark:bg-slate-800"><div className="bg-white p-4 dark:bg-slate-900"><div className="text-xs text-slate-500">State</div><div className="mt-1 font-semibold">{status.status}</div></div><div className="bg-white p-4 dark:bg-slate-900"><div className="text-xs text-slate-500">Blocking failures</div><div className="mt-1 font-financial font-semibold">{status.blockingFailuresCount}</div></div><div className="bg-white p-4 dark:bg-slate-900"><div className="text-xs text-slate-500">Warnings</div><div className="mt-1 font-financial font-semibold">{status.warningsCount}</div></div></div><section className="divide-y divide-slate-100 border border-slate-200 dark:divide-slate-800 dark:border-slate-800">{status.checks.map(check => <div key={check.code} className="flex gap-3 p-4">{check.passed ? <CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-emerald-600" /> : <CircleAlert className={check.severity === 'BLOCKING' ? 'mt-0.5 h-5 w-5 shrink-0 text-red-600' : 'mt-0.5 h-5 w-5 shrink-0 text-amber-600'} />}<div><h3 className="text-sm font-semibold">{check.title}</h3><p className="mt-1 text-xs text-slate-500">{check.message}</p></div></div>)}</section><div className="flex flex-wrap items-end justify-between gap-3 border-t border-slate-200 pt-4 dark:border-slate-800"><label className="min-w-[280px] flex-1 text-xs font-semibold">Reopen reason<input value={reason} onChange={e => setReason(e.target.value)} className="mt-1 w-full rounded-md border border-slate-300 p-2 text-sm dark:border-slate-700 dark:bg-slate-900" /></label>{status.status === 'CLOSED' ? <button disabled={busy || reason.trim().length < 5} onClick={() => void reopen()} className="inline-flex items-center gap-2 rounded-md border border-amber-300 px-3 py-2 text-xs font-semibold text-amber-800"><RotateCcw className="h-4 w-4" />Reopen Period</button> : <button disabled={busy || !status.canClose} onClick={() => void close()} className="inline-flex items-center gap-2 rounded-md bg-blue-600 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50"><LockKeyhole className="h-4 w-4" />Close Period</button>}</div></>}</div>;
};
