import React, { useState } from 'react';
import { ShieldCheck, Copy, Check, Key, AlertTriangle, X, Download } from 'lucide-react';
import { apiClient } from '../../api/client';

interface MfaEnrollmentModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
}

export const MfaEnrollmentModal: React.FC<MfaEnrollmentModalProps> = ({ isOpen, onClose, onSuccess }) => {
  const [step, setStep] = useState<'SETUP' | 'RECOVERY_CODES'>('SETUP');
  const [secretKey, setSecretKey] = useState('');
  const [qrUri, setQrUri] = useState('');
  const [recoveryCodes, setRecoveryCodes] = useState<string[]>([]);
  const [verificationCode, setVerificationCode] = useState('');
  const [copiedKey, setCopiedKey] = useState(false);
  const [copiedCodes, setCopiedCodes] = useState(false);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);

  React.useEffect(() => {
    if (isOpen) {
      setStep('SETUP');
      setError('');
      setVerificationCode('');
      setBusy(true);
      apiClient.post<{ secretKey: string; qrUri: string; recoveryCodes: string[] }>('/identity/mfa/enroll', {})
        .then((res) => {
          setBusy(false);
          if (res.data) {
            setSecretKey(res.data.secretKey);
            setQrUri(res.data.qrUri);
            setRecoveryCodes(res.data.recoveryCodes || []);
          } else {
            setError(res.error || 'Failed to generate MFA credentials');
          }
        });
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const handleCopyKey = () => {
    navigator.clipboard.writeText(secretKey);
    setCopiedKey(true);
    setTimeout(() => setCopiedKey(false), 2000);
  };

  const handleCopyCodes = () => {
    navigator.clipboard.writeText(recoveryCodes.join('\n'));
    setCopiedCodes(true);
    setTimeout(() => setCopiedCodes(false), 2000);
  };

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    if (verificationCode.length !== 6) {
      setError('Please enter the 6-digit code generated by your authenticator app.');
      return;
    }
    setBusy(true);
    setError('');
    const res = await apiClient.post<{ success: boolean }>('/identity/mfa/confirm', { code: verificationCode });
    setBusy(false);
    if (res.data?.success) {
      setStep('RECOVERY_CODES');
    } else {
      setError(res.error || 'Invalid 6-digit authentication code. Please check your authenticator clock.');
    }
  };

  const handleFinish = () => {
    onSuccess();
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4">
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl max-w-md w-full p-6 shadow-2xl space-y-5">
        <div className="flex justify-between items-center border-b border-slate-100 dark:border-slate-800 pb-3">
          <div className="flex items-center space-x-2">
            <div className="p-2 bg-emerald-50 dark:bg-emerald-950/60 text-emerald-600 dark:text-emerald-400 rounded-lg">
              <ShieldCheck className="w-5 h-5" />
            </div>
            <h3 className="font-bold text-slate-900 dark:text-slate-100 text-sm">
              {step === 'SETUP' ? 'Setup Two-Factor Authentication' : 'Emergency Recovery Codes'}
            </h3>
          </div>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 cursor-pointer">
            <X className="w-5 h-5" />
          </button>
        </div>

        {error && (
          <div className="p-3 bg-rose-50 dark:bg-rose-950/40 border border-rose-200 dark:border-rose-800 rounded-xl text-rose-700 dark:text-rose-300 text-xs flex items-center space-x-2">
            <AlertTriangle className="w-4 h-4 shrink-0" />
            <span>{error}</span>
          </div>
        )}

        {step === 'SETUP' ? (
          <div className="space-y-4 text-xs">
            <p className="text-slate-600 dark:text-slate-400">
              Scan this secret key or enter it manually into your authenticator app (Google Authenticator, 1Password, Authy):
            </p>

            <div className="p-3 bg-slate-50 dark:bg-slate-800/60 rounded-xl border border-slate-200 dark:border-slate-700 flex justify-between items-center">
              <div className="font-mono font-bold text-slate-800 dark:text-slate-200 break-all select-all pr-2">
                {secretKey || 'Generating key...'}
              </div>
              <button
                type="button"
                onClick={handleCopyKey}
                className="p-1.5 bg-white dark:bg-slate-700 border border-slate-200 dark:border-slate-600 rounded-lg text-slate-600 dark:text-slate-300 hover:text-slate-900 cursor-pointer flex items-center space-x-1"
              >
                {copiedKey ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
              </button>
            </div>

            <form onSubmit={handleVerify} className="space-y-3 pt-2">
              <label className="block text-slate-700 dark:text-slate-300 font-semibold">
                Enter 6-digit Authenticator Code:
              </label>
              <input
                type="text"
                maxLength={6}
                value={verificationCode}
                onChange={(e) => setVerificationCode(e.target.value.replace(/\D/g, ''))}
                placeholder="123456"
                required
                className="w-full text-center text-xl tracking-widest font-mono p-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-slate-900 dark:text-slate-100"
              />

              <button
                type="submit"
                disabled={busy || verificationCode.length !== 6}
                className="w-full py-2.5 bg-emerald-600 hover:bg-emerald-700 disabled:opacity-50 text-white font-bold rounded-xl shadow-xs transition-all cursor-pointer"
              >
                {busy ? 'Verifying...' : 'Enable Two-Factor Auth'}
              </button>
            </form>
          </div>
        ) : (
          <div className="space-y-4 text-xs">
            <p className="text-slate-600 dark:text-slate-400">
              Save these one-time emergency recovery codes in a secure location. If you lose access to your authenticator app, each code can be used once to regain access:
            </p>

            <div className="grid grid-cols-2 gap-2 p-3 bg-slate-50 dark:bg-slate-800/80 rounded-xl border border-slate-200 dark:border-slate-700 font-mono text-[11px]">
              {recoveryCodes.map((code, idx) => (
                <div key={idx} className="p-1 bg-white dark:bg-slate-700/60 rounded border border-slate-100 dark:border-slate-600 text-slate-800 dark:text-slate-200 text-center">
                  {code}
                </div>
              ))}
            </div>

            <div className="flex space-x-2">
              <button
                type="button"
                onClick={handleCopyCodes}
                className="flex-1 py-2 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 font-bold rounded-xl text-slate-700 dark:text-slate-300 flex items-center justify-center space-x-1.5 cursor-pointer"
              >
                {copiedCodes ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedCodes ? 'Copied' : 'Copy Codes'}</span>
              </button>
              <button
                type="button"
                onClick={handleFinish}
                className="flex-1 py-2 bg-emerald-600 hover:bg-emerald-700 font-bold text-white rounded-xl cursor-pointer"
              >
                Done
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
