import { DbQueryClient } from './db';

export async function applyPoint1Schema(client: DbQueryClient): Promise<void> {
  const statements = [
    `CREATE TABLE IF NOT EXISTS recurring_transaction_profiles (
      id VARCHAR(64) PRIMARY KEY,
      organization_id VARCHAR(64) NOT NULL,
      kind VARCHAR(20) NOT NULL,
      name VARCHAR(160) NOT NULL,
      status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
      frequency VARCHAR(20) NOT NULL,
      interval_count INT NOT NULL DEFAULT 1,
      start_date DATE NOT NULL,
      next_run_date DATE NOT NULL,
      end_date DATE,
      anchor_day INT NOT NULL,
      timezone VARCHAR(80) NOT NULL DEFAULT 'UTC',
      catch_up_policy VARCHAR(20) NOT NULL DEFAULT 'ALL',
      max_catch_up INT NOT NULL DEFAULT 12,
      template JSONB NOT NULL,
      auto_post BOOLEAN NOT NULL DEFAULT TRUE,
      created_by VARCHAR(64) NOT NULL,
      paused_at TIMESTAMP WITH TIME ZONE,
      version INT NOT NULL DEFAULT 1,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT uk_org_recurring_transaction_name UNIQUE (organization_id, name),
      CONSTRAINT uk_org_recurring_profile_id UNIQUE (organization_id, id),
      CONSTRAINT ck_recurring_transaction_type CHECK (kind IN ('INVOICE', 'BILL', 'EXPENSE')),
      CONSTRAINT ck_recurring_interval CHECK (interval_count > 0 AND max_catch_up > 0)
    )`,
    `CREATE TABLE IF NOT EXISTS recurring_transaction_occurrences (
      id VARCHAR(64) PRIMARY KEY,
      organization_id VARCHAR(64) NOT NULL,
      profile_id VARCHAR(64) NOT NULL,
      occurrence_key VARCHAR(180) NOT NULL,
      scheduled_for DATE NOT NULL,
      kind VARCHAR(20) NOT NULL,
      status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
      attempt_count INT NOT NULL DEFAULT 0,
      lease_owner VARCHAR(128),
      lease_expires_at TIMESTAMP WITH TIME ZONE,
      next_attempt_at TIMESTAMP WITH TIME ZONE,
      document_type VARCHAR(30),
      document_id VARCHAR(64),
      last_error_code VARCHAR(100),
      last_error_message TEXT,
      started_at TIMESTAMP WITH TIME ZONE,
      completed_at TIMESTAMP WITH TIME ZONE,
      quarantined_at TIMESTAMP WITH TIME ZONE,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT uk_org_recurring_occurrence_id UNIQUE (organization_id, id),
      CONSTRAINT uk_org_recurring_occurrence UNIQUE (organization_id, occurrence_key),
      CONSTRAINT fk_recurring_occurrence_profile FOREIGN KEY (organization_id, profile_id)
        REFERENCES recurring_transaction_profiles (organization_id, id) ON DELETE RESTRICT
    )`,
    `CREATE TABLE IF NOT EXISTS financial_reversals (
      id VARCHAR(64) PRIMARY KEY,
      organization_id VARCHAR(64) NOT NULL,
      source_type VARCHAR(50) NOT NULL,
      source_id VARCHAR(64) NOT NULL,
      reversal_journal_id VARCHAR(64) NOT NULL,
      reason TEXT NOT NULL,
      created_by VARCHAR(64) NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT uk_org_financial_reversal UNIQUE (organization_id, source_type, source_id)
    )`,
    `CREATE TABLE IF NOT EXISTS customer_advance_applications (
      id VARCHAR(64) PRIMARY KEY,
      organization_id VARCHAR(64) NOT NULL,
      advance_id VARCHAR(64) NOT NULL,
      invoice_id VARCHAR(64) NOT NULL,
      amount_applied NUMERIC(15, 2) NOT NULL,
      applied_date DATE NOT NULL,
      journal_entry_id VARCHAR(64) NOT NULL,
      status VARCHAR(20) NOT NULL DEFAULT 'POSTED',
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT uk_customer_advance_application_org_id UNIQUE (organization_id, id)
    )`,
    `CREATE TABLE IF NOT EXISTS vendor_advance_applications (
      id VARCHAR(64) PRIMARY KEY,
      organization_id VARCHAR(64) NOT NULL,
      advance_id VARCHAR(64) NOT NULL,
      bill_id VARCHAR(64) NOT NULL,
      amount_applied NUMERIC(15, 2) NOT NULL,
      applied_date DATE NOT NULL,
      journal_entry_id VARCHAR(64) NOT NULL,
      status VARCHAR(20) NOT NULL DEFAULT 'POSTED',
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT uk_vendor_advance_application_org_id UNIQUE (organization_id, id)
    )`,
    `CREATE TABLE IF NOT EXISTS fixed_asset_events (
      id VARCHAR(64) PRIMARY KEY,
      organization_id VARCHAR(64) NOT NULL,
      asset_id VARCHAR(64) NOT NULL,
      event_type VARCHAR(30) NOT NULL,
      effective_date DATE NOT NULL,
      amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
      journal_entry_id VARCHAR(64),
      reversal_of_event_id VARCHAR(64),
      reversed_by_event_id VARCHAR(64),
      metadata JSONB,
      created_by VARCHAR(64) NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS organization_invitations (
      id VARCHAR(64) PRIMARY KEY,
      organization_id VARCHAR(64) NOT NULL,
      email VARCHAR(320) NOT NULL,
      role VARCHAR(50) NOT NULL,
      token_hash VARCHAR(128) NOT NULL UNIQUE,
      invited_by_user_id VARCHAR(64) NOT NULL,
      accepted_by_user_id VARCHAR(64),
      expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
      accepted_at TIMESTAMP WITH TIME ZONE,
      revoked_at TIMESTAMP WITH TIME ZONE,
      revoked_by_user_id VARCHAR(64),
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS recovery_artifacts (
      id VARCHAR(64) PRIMARY KEY,
      organization_id VARCHAR(64) NOT NULL,
      status VARCHAR(30) NOT NULL,
      format_version INT NOT NULL,
      schema_version VARCHAR(80) NOT NULL,
      key_id VARCHAR(128) NOT NULL,
      manifest JSONB NOT NULL,
      envelope JSONB NOT NULL,
      created_by VARCHAR(64) NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS recovery_jobs (
      id VARCHAR(64) PRIMARY KEY,
      artifact_id VARCHAR(64) NOT NULL,
      target_organization_id VARCHAR(64) NOT NULL,
      staging_organization_id VARCHAR(64) NOT NULL,
      status VARCHAR(30) NOT NULL,
      reconciliation JSONB NOT NULL DEFAULT '[]'::jsonb,
      failure_reason TEXT,
      created_by VARCHAR(64) NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      promoted_by VARCHAR(64),
      promoted_at TIMESTAMP WITH TIME ZONE
    )`,
    `CREATE TABLE IF NOT EXISTS recovery_restore_jobs (
      id VARCHAR(64) PRIMARY KEY,
      organization_id VARCHAR(64) NOT NULL,
      artifact_id VARCHAR(64) NOT NULL,
      staging_organization_id VARCHAR(64) NOT NULL,
      status VARCHAR(30) NOT NULL,
      validation_result JSONB,
      reconciliation_result JSONB,
      requested_by VARCHAR(64) NOT NULL,
      validated_at TIMESTAMP WITH TIME ZONE,
      promoted_by VARCHAR(64),
      promoted_at TIMESTAMP WITH TIME ZONE,
      failure_code VARCHAR(100),
      failure_message TEXT,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS recovery_staging_rows (
      id VARCHAR(64) PRIMARY KEY,
      restore_job_id VARCHAR(64) NOT NULL,
      organization_id VARCHAR(64) NOT NULL,
      table_name VARCHAR(100) NOT NULL,
      row_key VARCHAR(180) NOT NULL,
      row_data JSONB NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT uk_recovery_staging_row UNIQUE (restore_job_id, table_name, row_key)
    )`,
    `CREATE TABLE IF NOT EXISTS fixed_asset_lifecycle_events (
      id VARCHAR(64) PRIMARY KEY,
      organization_id VARCHAR(64) NOT NULL,
      asset_id VARCHAR(64) NOT NULL,
      event_type VARCHAR(30) NOT NULL,
      event_date DATE NOT NULL,
      journal_entry_id VARCHAR(64) NOT NULL,
      amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
      status VARCHAR(20) NOT NULL DEFAULT 'POSTED',
      evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
      created_by VARCHAR(64) NOT NULL,
      reversed_at TIMESTAMP WITH TIME ZONE,
      reversed_by VARCHAR(64),
      reversal_reason TEXT,
      reversal_journal_id VARCHAR(64),
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS accounting_period_close_events (
      id VARCHAR(64) PRIMARY KEY,
      organization_id VARCHAR(64) NOT NULL,
      period_key VARCHAR(20) NOT NULL,
      event_type VARCHAR(20) NOT NULL,
      event_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
      actor_id VARCHAR(64) NOT NULL,
      reason TEXT NOT NULL,
      evidence JSONB NOT NULL
    )`,
    `CREATE INDEX IF NOT EXISTS idx_recurring_profiles_due ON recurring_transaction_profiles (status, next_run_date, organization_id, id)`,
    `CREATE INDEX IF NOT EXISTS idx_recurring_occurrences_claim ON recurring_transaction_occurrences (status, next_attempt_at, scheduled_for, id)`,
    `CREATE INDEX IF NOT EXISTS idx_recurring_occurrences_lease ON recurring_transaction_occurrences (status, lease_expires_at)`,
    `CREATE INDEX IF NOT EXISTS idx_fixed_asset_events_asset ON fixed_asset_events (organization_id, asset_id, effective_date)`,
    `CREATE INDEX IF NOT EXISTS idx_invitations_org_pending ON organization_invitations (organization_id, expires_at, created_at)`,
    `CREATE INDEX IF NOT EXISTS idx_recovery_artifacts_org_created ON recovery_artifacts (organization_id, created_at)`,
    `CREATE INDEX IF NOT EXISTS idx_recovery_jobs_org_status ON recovery_restore_jobs (organization_id, status, created_at)`,
    `CREATE INDEX IF NOT EXISTS idx_recovery_jobs_target_status ON recovery_jobs (target_organization_id, status)`,
    `CREATE UNIQUE INDEX IF NOT EXISTS uk_period_lock_org_period ON period_locks (organization_id, period_name) WHERE period_name IS NOT NULL`,
    `CREATE UNIQUE INDEX IF NOT EXISTS uk_journal_org_entry_number ON journal_entries (organization_id, entry_number)`,
    `CREATE UNIQUE INDEX IF NOT EXISTS uk_pending_org_invitation_email ON organization_invitations (organization_id, email) WHERE accepted_at IS NULL AND revoked_at IS NULL`,
  ];

  for (const statement of statements) {
    try {
      await client.query(statement);
    } catch (error) {
      if (process.env.NODE_ENV === 'production') throw error;
    }
  }

  const additiveStatements = [
    `ALTER TABLE organization_members ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'Active'`,
    `ALTER TABLE organization_members ADD COLUMN IF NOT EXISTS access_version INT NOT NULL DEFAULT 1`,
    `ALTER TABLE organization_members ADD COLUMN IF NOT EXISTS access_invalidated_at TIMESTAMP WITH TIME ZONE`,
    `ALTER TABLE organization_members ADD COLUMN IF NOT EXISTS revoked_at TIMESTAMP WITH TIME ZONE`,
    `ALTER TABLE organization_members ADD COLUMN IF NOT EXISTS revoked_by_user_id VARCHAR(64)`,
    `ALTER TABLE organization_members ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`,
    `ALTER TABLE accounting_period_closes ADD COLUMN IF NOT EXISTS close_evidence JSONB`,
    `ALTER TABLE accounting_period_closes ADD COLUMN IF NOT EXISTS state_version INT NOT NULL DEFAULT 1`,
    `ALTER TABLE fixed_asset_depreciation_entries ADD COLUMN IF NOT EXISTS reversed_at TIMESTAMP WITH TIME ZONE`,
    `ALTER TABLE fixed_asset_depreciation_entries ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'POSTED'`,
    `ALTER TABLE fixed_asset_depreciation_entries ADD COLUMN IF NOT EXISTS reversed_by VARCHAR(64)`,
    `ALTER TABLE fixed_asset_depreciation_entries ADD COLUMN IF NOT EXISTS reversal_reason TEXT`,
    `ALTER TABLE fixed_asset_depreciation_entries ADD COLUMN IF NOT EXISTS reversal_journal_id VARCHAR(64)`,
    `ALTER TABLE credit_notes ADD COLUMN IF NOT EXISTS journal_entry_id VARCHAR(64)`,
    `ALTER TABLE credit_notes ADD COLUMN IF NOT EXISTS reversed_at TIMESTAMP WITH TIME ZONE`,
    `ALTER TABLE credit_notes ADD COLUMN IF NOT EXISTS reversal_journal_id VARCHAR(64)`,
    `ALTER TABLE credit_notes ADD COLUMN IF NOT EXISTS reversal_reason TEXT`,
    `ALTER TABLE customer_refunds ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'POSTED'`,
    `ALTER TABLE ar_write_offs ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'POSTED'`,
    `ALTER TABLE ap_write_offs ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'POSTED'`,
    `ALTER TABLE vendor_credits ADD COLUMN IF NOT EXISTS reversed_at TIMESTAMP WITH TIME ZONE`,
    `ALTER TABLE vendor_credits ADD COLUMN IF NOT EXISTS reversal_journal_id VARCHAR(64)`,
    `ALTER TABLE vendor_credits ADD COLUMN IF NOT EXISTS reversal_reason TEXT`,
    `ALTER TABLE payments_made ADD COLUMN IF NOT EXISTS reversal_journal_id VARCHAR(64)`,
    `ALTER TABLE payments_made ADD COLUMN IF NOT EXISTS reversed_at TIMESTAMP WITH TIME ZONE`,
    `ALTER TABLE payments_made ADD COLUMN IF NOT EXISTS reversed_by VARCHAR(64)`,
    `ALTER TABLE payments_made ADD COLUMN IF NOT EXISTS reversal_reason TEXT`,
    `ALTER TABLE customer_refunds ADD COLUMN IF NOT EXISTS reversal_journal_id VARCHAR(64)`,
    `ALTER TABLE customer_refunds ADD COLUMN IF NOT EXISTS reversed_at TIMESTAMP WITH TIME ZONE`,
    `ALTER TABLE customer_refunds ADD COLUMN IF NOT EXISTS reversed_by VARCHAR(64)`,
    `ALTER TABLE customer_refunds ADD COLUMN IF NOT EXISTS reversal_reason TEXT`,
    `ALTER TABLE ar_write_offs ADD COLUMN IF NOT EXISTS reversal_journal_id VARCHAR(64)`,
    `ALTER TABLE ar_write_offs ADD COLUMN IF NOT EXISTS reversed_at TIMESTAMP WITH TIME ZONE`,
    `ALTER TABLE ar_write_offs ADD COLUMN IF NOT EXISTS reversed_by VARCHAR(64)`,
    `ALTER TABLE ar_write_offs ADD COLUMN IF NOT EXISTS reversal_reason TEXT`,
    `ALTER TABLE ap_write_offs ADD COLUMN IF NOT EXISTS reversal_journal_id VARCHAR(64)`,
    `ALTER TABLE ap_write_offs ADD COLUMN IF NOT EXISTS reversed_at TIMESTAMP WITH TIME ZONE`,
    `ALTER TABLE ap_write_offs ADD COLUMN IF NOT EXISTS reversed_by VARCHAR(64)`,
    `ALTER TABLE ap_write_offs ADD COLUMN IF NOT EXISTS reversal_reason TEXT`,
    `ALTER TABLE credit_note_applications ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'POSTED'`,
    `ALTER TABLE credit_note_applications ADD COLUMN IF NOT EXISTS reversed_at TIMESTAMP WITH TIME ZONE`,
    `ALTER TABLE credit_note_applications ADD COLUMN IF NOT EXISTS reversed_by VARCHAR(64)`,
    `ALTER TABLE debit_note_applications ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'POSTED'`,
    `ALTER TABLE debit_note_applications ADD COLUMN IF NOT EXISTS reversed_at TIMESTAMP WITH TIME ZONE`,
    `ALTER TABLE debit_note_applications ADD COLUMN IF NOT EXISTS reversed_by VARCHAR(64)`,
    `ALTER TABLE customer_advance_applications ADD COLUMN IF NOT EXISTS reversal_journal_id VARCHAR(64)`,
    `ALTER TABLE customer_advance_applications ADD COLUMN IF NOT EXISTS reversed_at TIMESTAMP WITH TIME ZONE`,
    `ALTER TABLE customer_advance_applications ADD COLUMN IF NOT EXISTS reversed_by VARCHAR(64)`,
    `ALTER TABLE customer_advance_applications ADD COLUMN IF NOT EXISTS reversal_reason TEXT`,
    `ALTER TABLE vendor_advance_applications ADD COLUMN IF NOT EXISTS reversal_journal_id VARCHAR(64)`,
    `ALTER TABLE vendor_advance_applications ADD COLUMN IF NOT EXISTS reversed_at TIMESTAMP WITH TIME ZONE`,
    `ALTER TABLE vendor_advance_applications ADD COLUMN IF NOT EXISTS reversed_by VARCHAR(64)`,
    `ALTER TABLE vendor_advance_applications ADD COLUMN IF NOT EXISTS reversal_reason TEXT`,
    `ALTER TABLE vendor_advances ADD COLUMN IF NOT EXISTS reversal_journal_id VARCHAR(64)`,
    `ALTER TABLE vendor_advances ADD COLUMN IF NOT EXISTS reversed_at TIMESTAMP WITH TIME ZONE`,
    `ALTER TABLE vendor_advances ADD COLUMN IF NOT EXISTS reversed_by VARCHAR(64)`,
    `ALTER TABLE vendor_advances ADD COLUMN IF NOT EXISTS reversal_reason TEXT`,
    `ALTER TABLE invoices ADD COLUMN IF NOT EXISTS source_occurrence_key VARCHAR(180)`,
    `ALTER TABLE bills ADD COLUMN IF NOT EXISTS source_occurrence_key VARCHAR(180)`,
    `ALTER TABLE expenses ADD COLUMN IF NOT EXISTS source_occurrence_key VARCHAR(180)`,
    `CREATE UNIQUE INDEX IF NOT EXISTS uk_invoice_org_occurrence ON invoices (organization_id, source_occurrence_key) WHERE source_occurrence_key IS NOT NULL`,
    `CREATE UNIQUE INDEX IF NOT EXISTS uk_bill_org_occurrence ON bills (organization_id, source_occurrence_key) WHERE source_occurrence_key IS NOT NULL`,
    `CREATE UNIQUE INDEX IF NOT EXISTS uk_expense_org_occurrence ON expenses (organization_id, source_occurrence_key) WHERE source_occurrence_key IS NOT NULL`,
    `CREATE INDEX IF NOT EXISTS idx_active_org_owners ON organization_members (organization_id, role, status)`,
  ];

  for (const statement of additiveStatements) {
    try {
      await client.query(statement);
    } catch (error) {
      // pg-mem support for ADD COLUMN IF NOT EXISTS varies. Fresh-memory tests
      // still receive the base Point-1 tables; PostgreSQL applies all columns.
      if (process.env.NODE_ENV === 'production') throw error;
    }
  }
}
