export type RiskTier = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

export interface PermissionMetadata {
  code: string;
  module: string;
  resource: string;
  action: string;
  risk: RiskTier;
  description: string;
  dependencies: string[];
}

export interface SodConflict {
  id: string;
  title: string;
  permissionA: string;
  permissionB: string;
  risk: 'MEDIUM' | 'HIGH' | 'CRITICAL';
  description: string;
  mitigation: string;
}

export const PERMISSIONS_REGISTRY: Record<string, PermissionMetadata> = {
  // ==========================================
  // 1. CUSTOMERS & RECEIVABLES
  // ==========================================
  'customers.view': {
    code: 'customers.view',
    module: 'Sales',
    resource: 'Customers',
    action: 'View',
    risk: 'LOW',
    description: 'View customer directory, contacts, and balances',
    dependencies: [],
  },
  'customers.create': {
    code: 'customers.create',
    module: 'Sales',
    resource: 'Customers',
    action: 'Create',
    risk: 'MEDIUM',
    description: 'Register new customer accounts',
    dependencies: ['customers.view'],
  },
  'customers.edit': {
    code: 'customers.edit',
    module: 'Sales',
    resource: 'Customers',
    action: 'Edit',
    risk: 'MEDIUM',
    description: 'Update customer billing address, GSTIN, and credit terms',
    dependencies: ['customers.view'],
  },
  'customers.archive': {
    code: 'customers.archive',
    module: 'Sales',
    resource: 'Customers',
    action: 'Archive',
    risk: 'MEDIUM',
    description: 'Archive inactive customer master records',
    dependencies: ['customers.view'],
  },

  // ==========================================
  // 2. ESTIMATES & QUOTATIONS
  // ==========================================
  'estimates.view': {
    code: 'estimates.view',
    module: 'Sales',
    resource: 'Estimates',
    action: 'View',
    risk: 'LOW',
    description: 'View quotation records and revisions',
    dependencies: [],
  },
  'estimates.create': {
    code: 'estimates.create',
    module: 'Sales',
    resource: 'Estimates',
    action: 'Create',
    risk: 'MEDIUM',
    description: 'Create draft quotations and proposals',
    dependencies: ['estimates.view', 'customers.view'],
  },
  'estimates.edit': {
    code: 'estimates.edit',
    module: 'Sales',
    resource: 'Estimates',
    action: 'Edit',
    risk: 'MEDIUM',
    description: 'Modify draft or sent quotations',
    dependencies: ['estimates.view'],
  },
  'estimates.send': {
    code: 'estimates.send',
    module: 'Sales',
    resource: 'Estimates',
    action: 'Send',
    risk: 'LOW',
    description: 'Dispatch quotation PDF to client email',
    dependencies: ['estimates.view'],
  },
  'estimates.convert': {
    code: 'estimates.convert',
    module: 'Sales',
    resource: 'Estimates',
    action: 'Convert',
    risk: 'HIGH',
    description: 'Convert accepted quotation into sales invoice',
    dependencies: ['estimates.view', 'invoices.create'],
  },
  'estimates.delete': {
    code: 'estimates.delete',
    module: 'Sales',
    resource: 'Estimates',
    action: 'Delete',
    risk: 'MEDIUM',
    description: 'Delete unaccepted draft quotations',
    dependencies: ['estimates.view'],
  },

  // ==========================================
  // 3. SALES ORDERS & DELIVERY CHALLANS
  // ==========================================
  'sales_orders.view': {
    code: 'sales_orders.view',
    module: 'Sales',
    resource: 'Sales Orders',
    action: 'View',
    risk: 'LOW',
    description: 'View sales orders and fulfillment commitments',
    dependencies: [],
  },
  'sales_orders.create': {
    code: 'sales_orders.create',
    module: 'Sales',
    resource: 'Sales Orders',
    action: 'Create',
    risk: 'MEDIUM',
    description: 'Issue confirmed sales orders',
    dependencies: ['sales_orders.view', 'customers.view'],
  },
  'sales_orders.edit': {
    code: 'sales_orders.edit',
    module: 'Sales',
    resource: 'Sales Orders',
    action: 'Edit',
    risk: 'MEDIUM',
    description: 'Update open sales order lines or quantities',
    dependencies: ['sales_orders.view'],
  },
  'sales_orders.convert': {
    code: 'sales_orders.convert',
    module: 'Sales',
    resource: 'Sales Orders',
    action: 'Convert',
    risk: 'HIGH',
    description: 'Convert confirmed sales order to invoice',
    dependencies: ['sales_orders.view', 'invoices.create'],
  },
  'sales_orders.cancel': {
    code: 'sales_orders.cancel',
    module: 'Sales',
    resource: 'Sales Orders',
    action: 'Cancel',
    risk: 'MEDIUM',
    description: 'Cancel open sales orders',
    dependencies: ['sales_orders.view'],
  },
  'delivery_challans.view': {
    code: 'delivery_challans.view',
    module: 'Sales',
    resource: 'Delivery Challans',
    action: 'View',
    risk: 'LOW',
    description: 'View goods transport delivery challans',
    dependencies: [],
  },
  'delivery_challans.create': {
    code: 'delivery_challans.create',
    module: 'Sales',
    resource: 'Delivery Challans',
    action: 'Create',
    risk: 'MEDIUM',
    description: 'Issue goods delivery challan for shipping',
    dependencies: ['delivery_challans.view', 'customers.view'],
  },

  // ==========================================
  // 4. INVOICES & RECEIVABLES
  // ==========================================
  'invoices.view': {
    code: 'invoices.view',
    module: 'Sales',
    resource: 'Invoices',
    action: 'View',
    risk: 'LOW',
    description: 'View sales invoices, line items, and balances',
    dependencies: [],
  },
  'invoices.create': {
    code: 'invoices.create',
    module: 'Sales',
    resource: 'Invoices',
    action: 'Create',
    risk: 'HIGH',
    description: 'Create and post sales invoices to General Ledger',
    dependencies: ['invoices.view', 'customers.view'],
  },
  'invoices.send': {
    code: 'invoices.send',
    module: 'Sales',
    resource: 'Invoices',
    action: 'Send',
    risk: 'LOW',
    description: 'Email tax invoice PDF to customer',
    dependencies: ['invoices.view'],
  },
  'invoices.void': {
    code: 'invoices.void',
    module: 'Sales',
    resource: 'Invoices',
    action: 'Void',
    risk: 'CRITICAL',
    description: 'Void posted sales invoice and reverse GL entries',
    dependencies: ['invoices.view'],
  },
  'invoices.write_off': {
    code: 'invoices.write_off',
    module: 'Sales',
    resource: 'Invoices',
    action: 'Write-Off',
    risk: 'CRITICAL',
    description: 'Write off uncollectible customer balance to bad debt',
    dependencies: ['invoices.view'],
  },

  // ==========================================
  // 5. CUSTOMER PAYMENTS & ADVANCES
  // ==========================================
  'customer_payments.view': {
    code: 'customer_payments.view',
    module: 'Sales',
    resource: 'Customer Payments',
    action: 'View',
    risk: 'LOW',
    description: 'View customer payment vouchers and receipts',
    dependencies: [],
  },
  'customer_payments.create': {
    code: 'customer_payments.create',
    module: 'Sales',
    resource: 'Customer Payments',
    action: 'Create',
    risk: 'HIGH',
    description: 'Record customer payment remittance against invoices',
    dependencies: ['customer_payments.view', 'invoices.view'],
  },
  'customer_payments.allocate': {
    code: 'customer_payments.allocate',
    module: 'Sales',
    resource: 'Customer Payments',
    action: 'Allocate',
    risk: 'HIGH',
    description: 'Apply unallocated customer advance to open invoices',
    dependencies: ['customer_payments.view', 'invoices.view'],
  },
  'customer_payments.reverse': {
    code: 'customer_payments.reverse',
    module: 'Sales',
    resource: 'Customer Payments',
    action: 'Reverse',
    risk: 'CRITICAL',
    description: 'Void customer payment and restore invoice balance',
    dependencies: ['customer_payments.view'],
  },

  // ==========================================
  // 6. CREDIT NOTES & REFUNDS
  // ==========================================
  'credit_notes.view': {
    code: 'credit_notes.view',
    module: 'Sales',
    resource: 'Credit Notes',
    action: 'View',
    risk: 'LOW',
    description: 'View credit note vouchers and balances',
    dependencies: [],
  },
  'credit_notes.create': {
    code: 'credit_notes.create',
    module: 'Sales',
    resource: 'Credit Notes',
    action: 'Create',
    risk: 'HIGH',
    description: 'Issue sales return credit note to GL',
    dependencies: ['credit_notes.view', 'customers.view'],
  },
  'credit_notes.apply': {
    code: 'credit_notes.apply',
    module: 'Sales',
    resource: 'Credit Notes',
    action: 'Apply',
    risk: 'HIGH',
    description: 'Apply credit balance to outstanding invoice',
    dependencies: ['credit_notes.view', 'invoices.view'],
  },
  'credit_notes.refund': {
    code: 'credit_notes.refund',
    module: 'Sales',
    resource: 'Credit Notes',
    action: 'Refund',
    risk: 'HIGH',
    description: 'Disburse bank refund for unapplied customer credit',
    dependencies: ['credit_notes.view'],
  },
  'credit_notes.void': {
    code: 'credit_notes.void',
    module: 'Sales',
    resource: 'Credit Notes',
    action: 'Void',
    risk: 'CRITICAL',
    description: 'Void unallocated credit note voucher in GL',
    dependencies: ['credit_notes.view'],
  },

  // ==========================================
  // 7. VENDORS & PROCUREMENT
  // ==========================================
  'vendors.view': {
    code: 'vendors.view',
    module: 'Purchases',
    resource: 'Vendors',
    action: 'View',
    risk: 'LOW',
    description: 'View supplier registry, bank accounts, and addresses',
    dependencies: [],
  },
  'vendors.create': {
    code: 'vendors.create',
    module: 'Purchases',
    resource: 'Vendors',
    action: 'Create',
    risk: 'MEDIUM',
    description: 'Register new vendor records',
    dependencies: ['vendors.view'],
  },
  'vendors.edit': {
    code: 'vendors.edit',
    module: 'Purchases',
    resource: 'Vendors',
    action: 'Edit',
    risk: 'MEDIUM',
    description: 'Update vendor banking and tax details',
    dependencies: ['vendors.view'],
  },
  'vendors.archive': {
    code: 'vendors.archive',
    module: 'Purchases',
    resource: 'Vendors',
    action: 'Archive',
    risk: 'MEDIUM',
    description: 'Archive inactive vendor accounts',
    dependencies: ['vendors.view'],
  },

  // ==========================================
  // 8. PURCHASE ORDERS
  // ==========================================
  'purchase_orders.view': {
    code: 'purchase_orders.view',
    module: 'Purchases',
    resource: 'Purchase Orders',
    action: 'View',
    risk: 'LOW',
    description: 'View purchase orders and committed purchase totals',
    dependencies: [],
  },
  'purchase_orders.create': {
    code: 'purchase_orders.create',
    module: 'Purchases',
    resource: 'Purchase Orders',
    action: 'Create',
    risk: 'MEDIUM',
    description: 'Create draft purchase orders to suppliers',
    dependencies: ['purchase_orders.view', 'vendors.view'],
  },
  'purchase_orders.edit': {
    code: 'purchase_orders.edit',
    module: 'Purchases',
    resource: 'Purchase Orders',
    action: 'Edit',
    risk: 'MEDIUM',
    description: 'Update draft PO quantities or pricing',
    dependencies: ['purchase_orders.view'],
  },
  'purchase_orders.submit': {
    code: 'purchase_orders.submit',
    module: 'Purchases',
    resource: 'Purchase Orders',
    action: 'Submit',
    risk: 'LOW',
    description: 'Submit PO for manager approval',
    dependencies: ['purchase_orders.view'],
  },
  'purchase_orders.approve': {
    code: 'purchase_orders.approve',
    module: 'Purchases',
    resource: 'Purchase Orders',
    action: 'Approve',
    risk: 'HIGH',
    description: 'Authorize PO spending above threshold',
    dependencies: ['purchase_orders.view'],
  },
  'purchase_orders.cancel': {
    code: 'purchase_orders.cancel',
    module: 'Purchases',
    resource: 'Purchase Orders',
    action: 'Cancel',
    risk: 'MEDIUM',
    description: 'Cancel unbilled purchase order commitments',
    dependencies: ['purchase_orders.view'],
  },
  'purchase_orders.convert_to_bill': {
    code: 'purchase_orders.convert_to_bill',
    module: 'Purchases',
    resource: 'Purchase Orders',
    action: 'Convert to Bill',
    risk: 'HIGH',
    description: 'Convert confirmed PO into a vendor bill',
    dependencies: ['purchase_orders.view', 'bills.create'],
  },

  // ==========================================
  // 9. VENDOR BILLS & AP
  // ==========================================
  'bills.view': {
    code: 'bills.view',
    module: 'Purchases',
    resource: 'Bills',
    action: 'View',
    risk: 'LOW',
    description: 'View vendor bills and AP due dates',
    dependencies: [],
  },
  'bills.create': {
    code: 'bills.create',
    module: 'Purchases',
    resource: 'Bills',
    action: 'Create',
    risk: 'HIGH',
    description: 'Post vendor bill to Accounts Payable and Expense GL',
    dependencies: ['bills.view', 'vendors.view'],
  },
  'bills.void': {
    code: 'bills.void',
    module: 'Purchases',
    resource: 'Bills',
    action: 'Void',
    risk: 'CRITICAL',
    description: 'Void posted vendor bill and reverse AP liability in GL',
    dependencies: ['bills.view'],
  },

  // ==========================================
  // 10. VENDOR PAYMENTS & ADVANCES
  // ==========================================
  'vendor_payments.view': {
    code: 'vendor_payments.view',
    module: 'Purchases',
    resource: 'Vendor Payments',
    action: 'View',
    risk: 'LOW',
    description: 'View vendor disbursement records and payment vouchers',
    dependencies: [],
  },
  'vendor_payments.create': {
    code: 'vendor_payments.create',
    module: 'Purchases',
    resource: 'Vendor Payments',
    action: 'Create',
    risk: 'HIGH',
    description: 'Disburse cash/bank payment settling vendor bills',
    dependencies: ['vendor_payments.view', 'bills.view'],
  },
  'vendor_payments.allocate': {
    code: 'vendor_payments.allocate',
    module: 'Purchases',
    resource: 'Vendor Payments',
    action: 'Allocate',
    risk: 'HIGH',
    description: 'Apply unallocated vendor advance to open bills',
    dependencies: ['vendor_payments.view', 'bills.view'],
  },
  'vendor_payments.reverse': {
    code: 'vendor_payments.reverse',
    module: 'Purchases',
    resource: 'Vendor Payments',
    action: 'Reverse',
    risk: 'CRITICAL',
    description: 'Void vendor payment disbursement and restore AP liability',
    dependencies: ['vendor_payments.view'],
  },
  'vendor_advances.view': {
    code: 'vendor_advances.view',
    module: 'Purchases',
    resource: 'Vendor Advances',
    action: 'View',
    risk: 'LOW',
    description: 'View vendor prepayments and advance asset vouchers',
    dependencies: [],
  },
  'vendor_advances.create': {
    code: 'vendor_advances.create',
    module: 'Purchases',
    resource: 'Vendor Advances',
    action: 'Create',
    risk: 'HIGH',
    description: 'Disburse advance payment to supplier before bill receipt',
    dependencies: ['vendor_advances.view', 'vendors.view'],
  },
  'vendor_advances.apply': {
    code: 'vendor_advances.apply',
    module: 'Purchases',
    resource: 'Vendor Advances',
    action: 'Apply',
    risk: 'HIGH',
    description: 'Apply vendor advance to reduce payable bill balance',
    dependencies: ['vendor_advances.view', 'bills.view'],
  },
  'vendor_advances.reverse': {
    code: 'vendor_advances.reverse',
    module: 'Purchases',
    resource: 'Vendor Advances',
    action: 'Reverse',
    risk: 'CRITICAL',
    description: 'Void unapplied vendor advance voucher',
    dependencies: ['vendor_advances.view'],
  },
  'vendor_credits.view': {
    code: 'vendor_credits.view',
    module: 'Purchases',
    resource: 'Vendor Credits',
    action: 'View',
    risk: 'LOW',
    description: 'View supplier debit notes and vendor credit balances',
    dependencies: [],
  },
  'vendor_credits.create': {
    code: 'vendor_credits.create',
    module: 'Purchases',
    resource: 'Vendor Credits',
    action: 'Create',
    risk: 'HIGH',
    description: 'Record supplier debit note / purchase return in GL',
    dependencies: ['vendor_credits.view', 'vendors.view'],
  },
  'vendor_credits.apply': {
    code: 'vendor_credits.apply',
    module: 'Purchases',
    resource: 'Vendor Credits',
    action: 'Apply',
    risk: 'HIGH',
    description: 'Apply vendor credit to reduce outstanding bill balance',
    dependencies: ['vendor_credits.view', 'bills.view'],
  },
  'vendor_credits.refund': {
    code: 'vendor_credits.refund',
    module: 'Purchases',
    resource: 'Vendor Credits',
    action: 'Refund',
    risk: 'HIGH',
    description: 'Receive bank refund for unapplied vendor credit',
    dependencies: ['vendor_credits.view'],
  },
  'vendor_credits.void': {
    code: 'vendor_credits.void',
    module: 'Purchases',
    resource: 'Vendor Credits',
    action: 'Void',
    risk: 'CRITICAL',
    description: 'Void unapplied vendor credit voucher',
    dependencies: ['vendor_credits.view'],
  },

  // ==========================================
  // 11. OPERATING EXPENSES
  // ==========================================
  'expenses.view': {
    code: 'expenses.view',
    module: 'Expenses',
    resource: 'Expenses',
    action: 'View',
    risk: 'LOW',
    description: 'View direct operating expenses and attached receipts',
    dependencies: [],
  },
  'expenses.create': {
    code: 'expenses.create',
    module: 'Expenses',
    resource: 'Expenses',
    action: 'Create',
    risk: 'HIGH',
    description: 'Post direct cash/bank operating expense to GL',
    dependencies: ['expenses.view', 'accounts.view'],
  },
  'expenses.edit_draft': {
    code: 'expenses.edit_draft',
    module: 'Expenses',
    resource: 'Expenses',
    action: 'Edit Draft',
    risk: 'MEDIUM',
    description: 'Edit draft or unsubmitted employee expense claims',
    dependencies: ['expenses.view'],
  },
  'expenses.submit': {
    code: 'expenses.submit',
    module: 'Expenses',
    resource: 'Expenses',
    action: 'Submit',
    risk: 'LOW',
    description: 'Submit expense claim for approval',
    dependencies: ['expenses.view'],
  },
  'expenses.approve': {
    code: 'expenses.approve',
    module: 'Expenses',
    resource: 'Expenses',
    action: 'Approve',
    risk: 'HIGH',
    description: 'Authorize employee expense reimbursement',
    dependencies: ['expenses.view'],
  },
  'expenses.void': {
    code: 'expenses.void',
    module: 'Expenses',
    resource: 'Expenses',
    action: 'Void',
    risk: 'CRITICAL',
    description: 'Void posted operating expense and reverse GL entries',
    dependencies: ['expenses.view'],
  },
  'expenses.attach_receipt': {
    code: 'expenses.attach_receipt',
    module: 'Expenses',
    resource: 'Expenses',
    action: 'Attach Receipt',
    risk: 'LOW',
    description: 'Upload digital receipt image or PDF to expense voucher',
    dependencies: ['expenses.view'],
  },

  // ==========================================
  // 12. ACCOUNTING & GENERAL LEDGER
  // ==========================================
  'accounts.view': {
    code: 'accounts.view',
    module: 'Accounting',
    resource: 'Chart of Accounts',
    action: 'View',
    risk: 'LOW',
    description: 'View Chart of Accounts tree and current balances',
    dependencies: [],
  },
  'accounts.create': {
    code: 'accounts.create',
    module: 'Accounting',
    resource: 'Chart of Accounts',
    action: 'Create',
    risk: 'MEDIUM',
    description: 'Add new ledger account in appropriate category',
    dependencies: ['accounts.view'],
  },
  'accounts.edit': {
    code: 'accounts.edit',
    module: 'Accounting',
    resource: 'Chart of Accounts',
    action: 'Edit',
    risk: 'HIGH',
    description: 'Rename account or update reporting classification',
    dependencies: ['accounts.view'],
  },
  'accounts.archive': {
    code: 'accounts.archive',
    module: 'Accounting',
    resource: 'Chart of Accounts',
    action: 'Archive',
    risk: 'HIGH',
    description: 'Archive unused account with zero lifetime balance',
    dependencies: ['accounts.view'],
  },
  'accounts.delete': {
    code: 'accounts.delete',
    module: 'Accounting',
    resource: 'Chart of Accounts',
    action: 'Delete',
    risk: 'CRITICAL',
    description: 'Delete an unused custom account with no financial or setup references',
    dependencies: ['accounts.view'],
  },
  'journals.view': {
    code: 'journals.view',
    module: 'Accounting',
    resource: 'Journals',
    action: 'View',
    risk: 'LOW',
    description: 'View manual journal entry vouchers and lines',
    dependencies: [],
  },
  'journals.create': {
    code: 'journals.create',
    module: 'Accounting',
    resource: 'Journals',
    action: 'Create',
    risk: 'MEDIUM',
    description: 'Draft manual journal entries for review',
    dependencies: ['journals.view', 'accounts.view'],
  },
  'journals.post': {
    code: 'journals.post',
    module: 'Accounting',
    resource: 'Journals',
    action: 'Post',
    risk: 'HIGH',
    description: 'Post manual journal entry directly to General Ledger',
    dependencies: ['journals.view', 'accounts.view'],
  },
  'journals.reverse': {
    code: 'journals.reverse',
    module: 'Accounting',
    resource: 'Journals',
    action: 'Reverse',
    risk: 'CRITICAL',
    description: 'Post reversing journal entry to cancel previous posting',
    dependencies: ['journals.view'],
  },
  'periods.view': {
    code: 'periods.view',
    module: 'Accounting',
    resource: 'Periods',
    action: 'View',
    risk: 'LOW',
    description: 'View accounting period lock status and close history',
    dependencies: [],
  },
  'periods.close': {
    code: 'periods.close',
    module: 'Accounting',
    resource: 'Periods',
    action: 'Close',
    risk: 'HIGH',
    description: 'Execute monthly/fiscal period close checklist',
    dependencies: ['periods.view'],
  },
  'periods.lock': {
    code: 'periods.lock',
    module: 'Accounting',
    resource: 'Periods',
    action: 'Lock',
    risk: 'HIGH',
    description: 'Set freeze date preventing backdated transaction entry',
    dependencies: ['periods.view'],
  },
  'periods.unlock': {
    code: 'periods.unlock',
    module: 'Accounting',
    resource: 'Periods',
    action: 'Unlock',
    risk: 'CRITICAL',
    description: 'Reopen locked accounting period (Requires Owner reason)',
    dependencies: ['periods.view'],
  },
  'opening_balances.view': {
    code: 'opening_balances.view',
    module: 'Accounting',
    resource: 'Opening Balances',
    action: 'View',
    risk: 'LOW',
    description: 'View historical opening balance schedule',
    dependencies: [],
  },
  'opening_balances.manage': {
    code: 'opening_balances.manage',
    module: 'Accounting',
    resource: 'Opening Balances',
    action: 'Manage',
    risk: 'CRITICAL',
    description: 'Set or adjust organization historical opening balances',
    dependencies: ['accounts.view', 'opening_balances.view'],
  },
  'fixed_assets.view': {
    code: 'fixed_assets.view',
    module: 'Accounting',
    resource: 'Fixed Assets',
    action: 'View',
    risk: 'LOW',
    description: 'View fixed asset registry and depreciation schedules',
    dependencies: [],
  },
  'fixed_assets.manage': {
    code: 'fixed_assets.manage',
    module: 'Accounting',
    resource: 'Fixed Assets',
    action: 'Manage',
    risk: 'HIGH',
    description: 'Register assets, post monthly depreciation, and disposals',
    dependencies: ['fixed_assets.view', 'accounts.view'],
  },

  // ==========================================
  // 13. BANKING & CASH OPERATIONS
  // ==========================================
  'banking.view': {
    code: 'banking.view',
    module: 'Banking',
    resource: 'Bank Accounts',
    action: 'View',
    risk: 'LOW',
    description: 'View bank account balances and transaction activity',
    dependencies: [],
  },
  'bank_accounts.create': {
    code: 'bank_accounts.create',
    module: 'Banking',
    resource: 'Bank Accounts',
    action: 'Create',
    risk: 'HIGH',
    description: 'Connect new bank or petty cash account',
    dependencies: ['banking.view', 'accounts.view'],
  },
  'bank_accounts.edit': {
    code: 'bank_accounts.edit',
    module: 'Banking',
    resource: 'Bank Accounts',
    action: 'Edit',
    risk: 'HIGH',
    description: 'Update bank routing, account number, or limits',
    dependencies: ['banking.view'],
  },
  'bank_transactions.view': {
    code: 'bank_transactions.view',
    module: 'Banking',
    resource: 'Bank Transactions',
    action: 'View',
    risk: 'LOW',
    description: 'View imported bank statement transaction lines',
    dependencies: ['banking.view'],
  },
  'bank_statements.import': {
    code: 'bank_statements.import',
    module: 'Banking',
    resource: 'Bank Statements',
    action: 'Import',
    risk: 'MEDIUM',
    description: 'Upload OFX/QIF/CSV bank statements into feed',
    dependencies: ['banking.view'],
  },
  'bank_reconciliation.view': {
    code: 'bank_reconciliation.view',
    module: 'Banking',
    resource: 'Reconciliation',
    action: 'View',
    risk: 'LOW',
    description: 'View bank reconciliation dashboard and matched items',
    dependencies: ['banking.view'],
  },
  'bank_reconciliation.match': {
    code: 'bank_reconciliation.match',
    module: 'Banking',
    resource: 'Reconciliation',
    action: 'Match',
    risk: 'MEDIUM',
    description: 'Match statement line against invoice/bill payment journal',
    dependencies: ['bank_reconciliation.view'],
  },
  'bank_reconciliation.reconcile': {
    code: 'bank_reconciliation.reconcile',
    module: 'Banking',
    resource: 'Reconciliation',
    action: 'Reconcile',
    risk: 'HIGH',
    description: 'Formally close and certify bank reconciliation session',
    dependencies: ['bank_reconciliation.view'],
  },
  'bank_reconciliation.unreconcile': {
    code: 'bank_reconciliation.unreconcile',
    module: 'Banking',
    resource: 'Reconciliation',
    action: 'Unreconcile',
    risk: 'HIGH',
    description: 'Break existing bank reconciliation match link',
    dependencies: ['bank_reconciliation.view'],
  },
  'bank_transfers.create': {
    code: 'bank_transfers.create',
    module: 'Banking',
    resource: 'Bank Transfers',
    action: 'Create',
    risk: 'HIGH',
    description: 'Post inter-bank transfer between accounts in GL',
    dependencies: ['banking.view', 'accounts.view'],
  },

  // ==========================================
  // 14. REPORTS & ANALYTICS
  // ==========================================
  'reports.view': {
    code: 'reports.view',
    module: 'Reports',
    resource: 'General Reports',
    action: 'View',
    risk: 'LOW',
    description: 'Access standard business reports',
    dependencies: [],
  },
  'reports.financial_statements': {
    code: 'reports.financial_statements',
    module: 'Reports',
    resource: 'Financial Statements',
    action: 'View',
    risk: 'HIGH',
    description: 'Access Balance Sheet, Profit & Loss, and Trial Balance',
    dependencies: ['reports.view'],
  },
  'reports.receivables': {
    code: 'reports.receivables',
    module: 'Reports',
    resource: 'Receivables Reports',
    action: 'View',
    risk: 'MEDIUM',
    description: 'View AR Aging, Customer Statements, and Collection summaries',
    dependencies: ['reports.view'],
  },
  'reports.payables': {
    code: 'reports.payables',
    module: 'Reports',
    resource: 'Payables Reports',
    action: 'View',
    risk: 'MEDIUM',
    description: 'View AP Aging, Vendor Statements, and Cash Requirements',
    dependencies: ['reports.view'],
  },
  'reports.gst': {
    code: 'reports.gst',
    module: 'Reports',
    resource: 'Tax Reports',
    action: 'View',
    risk: 'HIGH',
    description: 'View GSTR-1, GSTR-3B, and Tax Liability returns',
    dependencies: ['reports.view'],
  },
  'reports.bank': {
    code: 'reports.bank',
    module: 'Reports',
    resource: 'Bank Reports',
    action: 'View',
    risk: 'MEDIUM',
    description: 'View Bank Reconciliation Statement and Cash Forecasts',
    dependencies: ['reports.view'],
  },
  'reports.projects': {
    code: 'reports.projects',
    module: 'Reports',
    resource: 'Project Reports',
    action: 'View',
    risk: 'MEDIUM',
    description: 'View project profitability and WIP summaries',
    dependencies: ['reports.view'],
  },
  'reports.audit': {
    code: 'reports.audit',
    module: 'Reports',
    resource: 'Audit Reports',
    action: 'View',
    risk: 'HIGH',
    description: 'View tamper-evident audit logs and financial diagnostics',
    dependencies: ['reports.view'],
  },
  'reports.export': {
    code: 'reports.export',
    module: 'Reports',
    resource: 'Export',
    action: 'Export',
    risk: 'MEDIUM',
    description: 'Download CSV / Excel / PDF exports of financial reports',
    dependencies: ['reports.view'],
  },

  // ==========================================
  // 15. PROJECTS & TIME TRACKING
  // ==========================================
  'projects.view': {
    code: 'projects.view',
    module: 'Projects',
    resource: 'Projects',
    action: 'View',
    risk: 'LOW',
    description: 'View active projects, milestones, and task schedules',
    dependencies: [],
  },
  'projects.create': {
    code: 'projects.create',
    module: 'Projects',
    resource: 'Projects',
    action: 'Create',
    risk: 'MEDIUM',
    description: 'Create new project workspace and budget',
    dependencies: ['projects.view'],
  },
  'projects.edit': {
    code: 'projects.edit',
    module: 'Projects',
    resource: 'Projects',
    action: 'Edit',
    risk: 'MEDIUM',
    description: 'Update project deliverables, assignees, and deadlines',
    dependencies: ['projects.view'],
  },
  'projects.financials': {
    code: 'projects.financials',
    module: 'Projects',
    resource: 'Project Financials',
    action: 'View Financials',
    risk: 'HIGH',
    description: 'View project commercial margins, revenues, and actual costs',
    dependencies: ['projects.view'],
  },
  'projects.time_entries': {
    code: 'projects.time_entries',
    module: 'Projects',
    resource: 'Time Entries',
    action: 'Log Time',
    risk: 'LOW',
    description: 'Log billable and non-billable employee hours',
    dependencies: ['projects.view'],
  },
  'projects.invoice_time': {
    code: 'projects.invoice_time',
    module: 'Projects',
    resource: 'Time Billing',
    action: 'Invoice Time',
    risk: 'HIGH',
    description: 'Seal unbilled time entries and generate client invoice',
    dependencies: ['projects.view', 'invoices.create'],
  },

  // ==========================================
  // 16. ADMINISTRATION & SECURITY
  // ==========================================
  'users.view': {
    code: 'users.view',
    module: 'Settings',
    resource: 'Users',
    action: 'View',
    risk: 'LOW',
    description: 'View organization member roster and status',
    dependencies: [],
  },
  'users.invite': {
    code: 'users.invite',
    module: 'Settings',
    resource: 'Users',
    action: 'Invite',
    risk: 'MEDIUM',
    description: 'Send email invitations to new workspace members',
    dependencies: ['users.view'],
  },
  'users.deactivate': {
    code: 'users.deactivate',
    module: 'Settings',
    resource: 'Users',
    action: 'Deactivate',
    risk: 'HIGH',
    description: 'Revoke membership access for active members',
    dependencies: ['users.view'],
  },
  'roles.view': {
    code: 'roles.view',
    module: 'Settings',
    resource: 'Roles',
    action: 'View',
    risk: 'LOW',
    description: 'View system and custom role definitions',
    dependencies: [],
  },
  'roles.manage': {
    code: 'roles.manage',
    module: 'Settings',
    resource: 'Roles',
    action: 'Manage',
    risk: 'CRITICAL',
    description: 'Create, clone, or modify custom roles and permissions',
    dependencies: ['roles.view'],
  },
  'settings.view': {
    code: 'settings.view',
    module: 'Settings',
    resource: 'Settings',
    action: 'View',
    risk: 'LOW',
    description: 'View organization profile, address, and preferences',
    dependencies: [],
  },
  'settings.manage': {
    code: 'settings.manage',
    module: 'Settings',
    resource: 'Settings',
    action: 'Manage',
    risk: 'HIGH',
    description: 'Modify company profile, branding, prefixes, and terms',
    dependencies: ['settings.view'],
  },
  'settings.financial_config': {
    code: 'settings.financial_config',
    module: 'Settings',
    resource: 'Financial Config',
    action: 'Manage Financial Config',
    risk: 'CRITICAL',
    description: 'Modify control accounts, GSTIN, and tax clearing accounts',
    dependencies: ['settings.view', 'accounts.view'],
  },
  'approvals.manage': {
    code: 'approvals.manage',
    module: 'Settings',
    resource: 'Approvals',
    action: 'Manage',
    risk: 'HIGH',
    description: 'Configure entity threshold limits and approver assignments',
    dependencies: ['settings.view'],
  },
  'audit.view': {
    code: 'audit.view',
    module: 'Settings',
    resource: 'Audit Logs',
    action: 'View',
    risk: 'HIGH',
    description: 'Access full cryptographic audit stream and actions',
    dependencies: [],
  },
  'security.manage': {
    code: 'security.manage',
    module: 'Settings',
    resource: 'Security',
    action: 'Manage',
    risk: 'CRITICAL',
    description: 'Configure workspace 2FA enforcement and session rules',
    dependencies: ['settings.view'],
  },
  'backup.view': {
    code: 'backup.view',
    module: 'Settings',
    resource: 'Backups',
    action: 'View',
    risk: 'HIGH',
    description: 'View available backup snapshots and recovery jobs',
    dependencies: [],
  },
  'backup.create': {
    code: 'backup.create',
    module: 'Settings',
    resource: 'Backups',
    action: 'Create',
    risk: 'HIGH',
    description: 'Generate encrypted point-in-time organization backup',
    dependencies: ['backup.view'],
  },
  'backup.restore': {
    code: 'backup.restore',
    module: 'Settings',
    resource: 'Backups',
    action: 'Restore',
    risk: 'CRITICAL',
    description: 'Restore backup database (Owner Only)',
    dependencies: ['backup.view'],
  },
};

export type PermissionCode = keyof typeof PERMISSIONS_REGISTRY;
export const ALL_PERMISSION_CODES: PermissionCode[] = Object.keys(PERMISSIONS_REGISTRY) as PermissionCode[];

// ==========================================
// 8 SYSTEM ROLE TEMPLATES
// ==========================================
export const SYSTEM_ROLE_PERMISSIONS: Record<string, PermissionCode[]> = {
  Owner: [...ALL_PERMISSION_CODES],

  Admin: ALL_PERMISSION_CODES.filter(
    (code) => code !== 'backup.restore' && code !== 'periods.unlock' && code !== 'settings.financial_config'
  ),

  'Finance Manager': [
    'customers.view', 'customers.create', 'customers.edit',
    'estimates.view', 'estimates.create', 'estimates.edit', 'estimates.send', 'estimates.convert',
    'sales_orders.view', 'sales_orders.create', 'sales_orders.edit', 'sales_orders.convert',
    'delivery_challans.view', 'delivery_challans.create',
    'invoices.view', 'invoices.create', 'invoices.send', 'invoices.void', 'invoices.write_off',
    'customer_payments.view', 'customer_payments.create', 'customer_payments.allocate', 'customer_payments.reverse',
    'credit_notes.view', 'credit_notes.create', 'credit_notes.apply', 'credit_notes.refund', 'credit_notes.void',
    'vendors.view', 'vendors.create', 'vendors.edit',
    'purchase_orders.view', 'purchase_orders.create', 'purchase_orders.edit', 'purchase_orders.submit', 'purchase_orders.approve', 'purchase_orders.cancel', 'purchase_orders.convert_to_bill',
    'bills.view', 'bills.create', 'bills.void',
    'vendor_payments.view', 'vendor_payments.create', 'vendor_payments.allocate', 'vendor_payments.reverse',
    'vendor_advances.view', 'vendor_advances.create', 'vendor_advances.apply', 'vendor_advances.reverse',
    'vendor_credits.view', 'vendor_credits.create', 'vendor_credits.apply', 'vendor_credits.refund', 'vendor_credits.void',
    'expenses.view', 'expenses.create', 'expenses.edit_draft', 'expenses.submit', 'expenses.approve', 'expenses.void', 'expenses.attach_receipt',
    'accounts.view', 'accounts.create', 'accounts.edit', 'accounts.archive', 'accounts.delete',
    'journals.view', 'journals.create', 'journals.post', 'journals.reverse',
    'periods.view', 'periods.close', 'periods.lock',
    'opening_balances.view', 'opening_balances.manage',
    'fixed_assets.view', 'fixed_assets.manage',
    'banking.view', 'bank_accounts.create', 'bank_accounts.edit', 'bank_transactions.view', 'bank_statements.import', 'bank_reconciliation.view', 'bank_reconciliation.match', 'bank_reconciliation.reconcile', 'bank_reconciliation.unreconcile', 'bank_transfers.create',
    'reports.view', 'reports.financial_statements', 'reports.receivables', 'reports.payables', 'reports.gst', 'reports.bank', 'reports.projects', 'reports.audit', 'reports.export',
    'projects.view', 'projects.create', 'projects.edit', 'projects.financials', 'projects.time_entries', 'projects.invoice_time',
    'roles.view', 'settings.view', 'approvals.manage', 'audit.view', 'backup.view', 'backup.create',
  ],

  Accountant: [
    'customers.view', 'customers.create', 'customers.edit',
    'estimates.view', 'estimates.create', 'estimates.edit', 'estimates.send', 'estimates.convert',
    'sales_orders.view', 'sales_orders.create', 'sales_orders.edit', 'sales_orders.convert',
    'delivery_challans.view', 'delivery_challans.create',
    'invoices.view', 'invoices.create', 'invoices.send',
    'customer_payments.view', 'customer_payments.create', 'customer_payments.allocate',
    'credit_notes.view', 'credit_notes.create', 'credit_notes.apply', 'credit_notes.refund',
    'vendors.view', 'vendors.create', 'vendors.edit',
    'purchase_orders.view', 'purchase_orders.create', 'purchase_orders.edit', 'purchase_orders.submit', 'purchase_orders.convert_to_bill',
    'bills.view', 'bills.create',
    'vendor_payments.view', 'vendor_payments.allocate',
    'vendor_advances.view', 'vendor_advances.apply',
    'vendor_credits.view', 'vendor_credits.create', 'vendor_credits.apply', 'vendor_credits.refund',
    'expenses.view', 'expenses.create', 'expenses.edit_draft', 'expenses.submit', 'expenses.attach_receipt',
    'accounts.view', 'accounts.create',
    'journals.view', 'journals.create', 'journals.post',
    'periods.view', 'periods.close', 'periods.lock',
    'opening_balances.view',
    'fixed_assets.view', 'fixed_assets.manage',
    'banking.view', 'bank_transactions.view', 'bank_statements.import', 'bank_reconciliation.view', 'bank_reconciliation.match', 'bank_reconciliation.reconcile', 'bank_transfers.create',
    'reports.view', 'reports.financial_statements', 'reports.receivables', 'reports.payables', 'reports.gst', 'reports.bank', 'reports.projects', 'reports.export',
    'projects.view', 'projects.create', 'projects.edit', 'projects.financials', 'projects.time_entries', 'projects.invoice_time',
    'settings.view',
  ],

  Approver: [
    'estimates.view',
    'sales_orders.view',
    'invoices.view',
    'purchase_orders.view', 'purchase_orders.approve',
    'bills.view',
    'vendor_payments.view',
    'expenses.view', 'expenses.approve',
    'reports.view',
  ],

  Sales: [
    'customers.view', 'customers.create', 'customers.edit',
    'estimates.view', 'estimates.create', 'estimates.edit', 'estimates.send', 'estimates.convert', 'estimates.delete',
    'sales_orders.view', 'sales_orders.create', 'sales_orders.edit', 'sales_orders.convert', 'sales_orders.cancel',
    'delivery_challans.view', 'delivery_challans.create',
    'invoices.view', 'invoices.create', 'invoices.send',
    'customer_payments.view', 'customer_payments.create', 'customer_payments.allocate',
    'credit_notes.view', 'credit_notes.apply',
    'expenses.view', 'expenses.edit_draft', 'expenses.submit', 'expenses.attach_receipt',
    'reports.view', 'reports.receivables', 'reports.export',
    'projects.view', 'projects.create', 'projects.edit', 'projects.time_entries', 'projects.invoice_time',
  ],

  Purchase: [
    'vendors.view', 'vendors.create', 'vendors.edit',
    'purchase_orders.view', 'purchase_orders.create', 'purchase_orders.edit', 'purchase_orders.submit', 'purchase_orders.cancel', 'purchase_orders.convert_to_bill',
    'bills.view', 'bills.create',
    'vendor_advances.view',
    'vendor_credits.view',
    'expenses.view', 'expenses.edit_draft', 'expenses.submit', 'expenses.attach_receipt',
    'reports.view', 'reports.payables', 'reports.export',
    'projects.view', 'projects.time_entries',
  ],

  Viewer: [
    'customers.view',
    'estimates.view',
    'sales_orders.view',
    'delivery_challans.view',
    'invoices.view',
    'customer_payments.view',
    'credit_notes.view',
    'vendors.view',
    'purchase_orders.view',
    'bills.view',
    'vendor_payments.view',
    'vendor_advances.view',
    'vendor_credits.view',
    'expenses.view',
    'accounts.view',
    'journals.view',
    'periods.view',
    'opening_balances.view',
    'fixed_assets.view',
    'banking.view',
    'bank_transactions.view',
    'bank_reconciliation.view',
    'reports.view',
    'reports.financial_statements',
    'reports.receivables',
    'reports.payables',
    'reports.gst',
    'reports.bank',
    'reports.projects',
    'reports.audit',
    'projects.view',
    'projects.financials',
  ],
};

// ==========================================
// SEGREGATION OF DUTIES (SOD) CONFLICTS
// ==========================================
export const SOD_CONFLICTS: SodConflict[] = [
  {
    id: 'SOD-001',
    title: 'Vendor Master & Disbursement Pairing',
    permissionA: 'vendors.create',
    permissionB: 'vendor_payments.create',
    risk: 'CRITICAL',
    description: 'Actor can create fictitious suppliers and immediately disburse cash payments to them.',
    mitigation: 'Separate vendor master maintenance from payment disbursement execution.',
  },
  {
    id: 'SOD-002',
    title: 'Bill Entry & Payment Disbursement Pairing',
    permissionA: 'bills.create',
    permissionB: 'vendor_payments.create',
    risk: 'HIGH',
    description: 'Actor can enter vendor bills and execute payments without secondary authorization.',
    mitigation: 'Require dual authorization or assign bill entry and payment execution to separate roles.',
  },
  {
    id: 'SOD-003',
    title: 'Invoicing & Bad Debt Write-Off Pairing',
    permissionA: 'invoices.create',
    permissionB: 'invoices.write_off',
    risk: 'CRITICAL',
    description: 'Actor can record sales invoices and write off balances to conceal misappropriated cash.',
    mitigation: 'Restrict bad debt write-offs strictly to Owner or Finance Manager.',
  },
  {
    id: 'SOD-004',
    title: 'Journal Posting & Bank Reconciliation Pairing',
    permissionA: 'journals.post',
    permissionB: 'bank_reconciliation.reconcile',
    risk: 'HIGH',
    description: 'Actor can post arbitrary journal adjustments to bank accounts and certify reconciliation.',
    mitigation: 'Separate journal entry rights from formal bank reconciliation certification.',
  },
  {
    id: 'SOD-005',
    title: 'PO Creation & Self-Approval Pairing',
    permissionA: 'purchase_orders.create',
    permissionB: 'purchase_orders.approve',
    risk: 'HIGH',
    description: 'Actor can issue purchase orders and approve their own commitments without oversight.',
    mitigation: 'Enforce allow_self_approval = false in organization approval settings.',
  },
  {
    id: 'SOD-006',
    title: 'Period Close & Period Unlock Pairing',
    permissionA: 'periods.close',
    permissionB: 'periods.unlock',
    risk: 'CRITICAL',
    description: 'Actor can close accounting periods and unilaterally unlock past periods to alter ledgers.',
    mitigation: 'Period unlock must remain exclusive to Owner with mandatory audit justification.',
  },
];

export function detectSodConflicts(permissions: string[]): SodConflict[] {
  const permSet = new Set(permissions);
  return SOD_CONFLICTS.filter(
    (conflict) => permSet.has(conflict.permissionA) && permSet.has(conflict.permissionB)
  );
}

// ==========================================
// LEGACY TO GRANULAR PERMISSION MAPPING
// ==========================================
export const LEGACY_TO_GRANULAR_MAP: Record<string, PermissionCode[]> = {
  'invoices.view': ['invoices.view'],
  'invoices.create': ['invoices.create'],
  'invoices.edit': ['estimates.edit', 'sales_orders.edit'],
  'invoices.delete': ['invoices.void', 'invoices.write_off'],
  'invoices.approve': ['estimates.convert', 'sales_orders.convert'],
  'invoices.receive_payment': [
    'customer_payments.create',
    'customer_payments.allocate',
    'customer_payments.reverse',
  ],

  'purchases.view': ['bills.view', 'purchase_orders.view'],
  'purchases.create': ['bills.create', 'purchase_orders.create'],
  'purchases.edit': ['vendors.edit', 'purchase_orders.edit'],
  'purchases.delete': ['bills.void', 'purchase_orders.cancel', 'vendor_credits.void'],
  'purchases.approve': ['purchase_orders.approve', 'purchase_orders.convert_to_bill'],
  'purchases.pay': ['vendor_payments.create'],

  'expenses.view': ['expenses.view'],
  'expenses.create': ['expenses.create'],

  'accounting.view': ['accounts.view', 'journals.view', 'periods.view'],
  'accounting.post': ['journals.post'],

  'banking.view': ['banking.view'],
  'banking.import': ['bank_statements.import'],
  'banking.match': ['bank_reconciliation.match'],
  'banking.reconcile': ['bank_reconciliation.reconcile'],
  'banking.unreconcile': ['bank_reconciliation.unreconcile'],
  'banking.rules.manage': ['banking.view'],

  'reports.view': ['reports.view'],
  'reports.export': ['reports.export'],

  'audit.view': ['audit.view', 'reports.audit'],

  'settings.manage_users': ['users.view', 'users.invite', 'users.deactivate', 'roles.manage'],
  'settings.manage_taxes': ['reports.gst'],
  'settings.close_period': ['periods.close', 'periods.lock'],
  'settings.backup': ['backup.view', 'backup.create'],
  'settings.restore': ['backup.restore'],
  'settings.approvals': ['approvals.manage'],
  'settings.manage_accounts': ['accounts.create', 'accounts.edit', 'accounts.archive', 'accounts.delete'],
  'settings.manage_budgets': ['reports.view'],
  'settings.manage_numbering': ['settings.manage'],
  'migration.import': ['opening_balances.manage'],
};
